"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import {
  Compass,
  Users,
  MapPin,
  Sparkles,
  ArrowRight,
  Globe,
  Calendar,
  MessageSquare,
  Search,
  Star,
  CloudSun,
  Mountain,
  Palmtree,
  Plane,
  Heart,
  Zap,
  
  ChevronRight,
  Shield,
  Clock,
  TrendingUp,
  Play,
  Waves,
} from "lucide-react";
import AITripBuilderModal from "@/components/ai/AITripBuilderModal";
import MiniCalendar from "@/components/ui/MiniCalendar";
import Logo from "@/components/Logo";
import { GlassCard, Button, Badge, Avatar } from "@/components/ui";

/* ═══════════════════════════════════════════════════════════════════════════
   DATA
   ═══════════════════════════════════════════════════════════════════════ */

const HERO_DESTINATIONS = [
  "Santorini, Greece",
  "Kyoto, Japan",
  "Bali, Indonesia",
  "Barcelona, Spain",
  "Machu Picchu, Peru",
  "Amalfi Coast, Italy",
  "Banff, Canada",
  "Cape Town, South Africa",
];

const TRENDING_TRIPS = [
  {
    id: "1",
    title: "Greek Island Hopping",
    destination: "Santorini & Mykonos, Greece",
    image: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=600&h=400&fit=crop",
    dates: "Jul 12 – Jul 22",
    price: "$2,340",
    rating: 4.9,
    reviews: 234,
    spots: 3,
    maxSpots: 8,
    tags: ["Beach", "Culture"],
    creator: { name: "Elena K.", avatar: null },
    isAI: false,
  },
  {
    id: "2",
    title: "Tokyo Neon Nights & Zen Gardens",
    destination: "Tokyo & Kyoto, Japan",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&h=400&fit=crop",
    dates: "Aug 5 – Aug 18",
    price: "$3,120",
    rating: 4.8,
    reviews: 189,
    spots: 5,
    maxSpots: 10,
    tags: ["City", "Food"],
    creator: { name: "AI Trippy", avatar: null },
    isAI: true,
  },
  {
    id: "3",
    title: "Bali Wellness Retreat",
    destination: "Ubud & Seminyak, Bali",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&h=400&fit=crop",
    dates: "Sep 1 – Sep 10",
    price: "$1,890",
    rating: 4.9,
    reviews: 312,
    spots: 2,
    maxSpots: 6,
    tags: ["Wellness", "Nature"],
    creator: { name: "Maya R.", avatar: null },
    isAI: false,
  },
  {
    id: "4",
    title: "Patagonia Trek Adventure",
    destination: "Torres del Paine, Chile",
    image: "https://images.unsplash.com/photo-1531761535209-180857e963b9?w=600&h=400&fit=crop",
    dates: "Oct 8 – Oct 20",
    price: "$2,780",
    rating: 4.7,
    reviews: 98,
    spots: 4,
    maxSpots: 8,
    tags: ["Adventure", "Nature"],
    creator: { name: "AI Trippy", avatar: null },
    isAI: true,
  },
  {
    id: "5",
    title: "Amalfi Coast Road Trip",
    destination: "Naples to Positano, Italy",
    image: "https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?w=600&h=400&fit=crop",
    dates: "Jun 20 – Jun 28",
    price: "$2,100",
    rating: 4.8,
    reviews: 276,
    spots: 6,
    maxSpots: 10,
    tags: ["Road Trip", "Food"],
    creator: { name: "Luca T.", avatar: null },
    isAI: false,
  },
  {
    id: "6",
    title: "Northern Lights Chase",
    destination: "Tromsø & Lofoten, Norway",
    image: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=600&h=400&fit=crop",
    dates: "Nov 15 – Nov 24",
    price: "$3,450",
    rating: 4.9,
    reviews: 156,
    spots: 3,
    maxSpots: 6,
    tags: ["Nature", "Photography"],
    creator: { name: "AI Trippy", avatar: null },
    isAI: true,
  },
];

const AI_STEPS = [
  { icon: MessageSquare, label: "Tell us your vibe", desc: "Beach? Mountains? City? Just say the word." },
  { icon: Sparkles, label: "AI builds your trip", desc: "Smart itinerary with flights, stays & activities." },
  { icon: Users, label: "Invite your crew", desc: "Share the plan — everyone can edit & vote." },
  { icon: Plane, label: "Pack & go", desc: "Real-time updates, chat & day-by-day guides." },
];

const PREFERENCES = [
  { icon: Palmtree, label: "Beach & Islands", color: "text-accent-600" },
  { icon: Mountain, label: "Mountains", color: "text-trippy-600" },
  { icon: Globe, label: "City Breaks", color: "text-trippy-300" },
  { icon: Waves, label: "Adventure", color: "text-accent-500" },
  { icon: CloudSun, label: "Tropical", color: "text-warning" },
  { icon: Star, label: "Luxury", color: "text-accent-300" },
];

const FEATURES = [
  {
    icon: MapPin,
    title: "Plan Together",
    desc: "Build itineraries collaboratively with your travel companions in real-time.",
  },
  {
    icon: Sparkles,
    title: "AI-Powered Trips",
    desc: "Get complete trip plans generated by AI — flights, hotels, activities & budget.",
  },
  {
    icon: Users,
    title: "Invite Friends",
    desc: "Share trips with friends and family. Everyone can contribute ideas and vote.",
  },
  {
    icon: MessageSquare,
    title: "Group Chat",
    desc: "Discuss plans, share links, and coordinate without leaving the app.",
  },
  {
    icon: Calendar,
    title: "Day-by-Day Plans",
    desc: "Organize activities into daily plans with time slots, maps & budgets.",
  },
  {
    icon: Globe,
    title: "Discover & Join Trips",
    desc: "Browse public itineraries from real travelers & verified hosts. Join instantly.",
  },
];

const TESTIMONIALS = [
  {
    name: "Sarah M.",
    role: "Solo Traveler",
    text: "Trippy's AI planned my entire 2-week Japan trip in minutes. Every recommendation was spot-on!",
    rating: 5,
  },
  {
    name: "James & Priya",
    role: "Couple",
    text: "We used to fight over trip planning. Now we collaborate on Trippy and it's actually fun.",
    rating: 5,
  },
  {
    name: "The Wanderers",
    role: "Group of 6",
    text: "Coordinating 6 people across 3 timezones? Trippy made it seamless. Best group trip ever.",
    rating: 5,
  },
];

const STATS = [
  { value: "50K+", label: "Trips Created", icon: Globe },
  { value: "120K+", label: "Happy Travelers", icon: Users },
  { value: "190+", label: "Countries Covered", icon: MapPin },
  { value: "4.9", label: "App Rating", icon: Star },
];

/* ═══════════════════════════════════════════════════════════════════════════
   ANIMATION VARIANTS
   ═══════════════════════════════════════════════════════════════════════ */

const fadeUp = {
  hidden: { opacity: 0, y: 30 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.1, duration: 0.6, ease: "easeOut" as const },
  }),
};

const staggerContainer = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.08 } },
};

const fadeIn = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, ease: "easeOut" as const },
  },
};

/* ═══════════════════════════════════════════════════════════════════════════
   HERO TYPING EFFECT
   ═══════════════════════════════════════════════════════════════════════ */

function useTypingEffect(words: string[], typingSpeed = 80, pause = 2000) {
  const [text, setText] = useState("");
  const [wordIndex, setWordIndex] = useState(0);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    const current = words[wordIndex];

    const timeout = setTimeout(
      () => {
        if (!isDeleting) {
          setText(current.slice(0, text.length + 1));
          if (text.length + 1 === current.length) {
            setTimeout(() => setIsDeleting(true), pause);
          }
        } else {
          setText(current.slice(0, text.length - 1));
          if (text.length === 0) {
            setIsDeleting(false);
            setWordIndex((prev) => (prev + 1) % words.length);
          }
        }
      },
      isDeleting ? typingSpeed / 2 : typingSpeed
    );

    return () => clearTimeout(timeout);
  }, [text, wordIndex, isDeleting, words, typingSpeed, pause]);

  return text;
}

/* ═══════════════════════════════════════════════════════════════════════════
   PAGE
   ═══════════════════════════════════════════════════════════════════════ */

export default function LandingPage() {
  const typedDestination = useTypingEffect(HERO_DESTINATIONS, 70, 1800);
  const [activeAIStep, setActiveAIStep] = useState(0);
  const [selectedPrefs, setSelectedPrefs] = useState<string[]>(["Beach & Islands", "City Breaks"]);
  const [hoveredTrip, setHoveredTrip] = useState<string | null>(null);
  const [showAITooltip, setShowAITooltip] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [activeFilters, setActiveFilters] = useState<string[]>([]);
  const [showAIBuilder, setShowAIBuilder] = useState(false);
  const [isSearchFocused, setIsSearchFocused] = useState(false);
  const [showDatePicker, setShowDatePicker] = useState(false);
  const [startDate, setStartDate] = useState<Date | null>(null);
  const [endDate, setEndDate] = useState<Date | null>(null);

  const isSearchActive = isSearchFocused || searchQuery.length > 0 || activeFilters.length > 0 || (startDate !== null || endDate !== null);

  // Auto-cycle AI steps
  useEffect(() => {
    const interval = setInterval(() => {
      setActiveAIStep((prev) => (prev + 1) % AI_STEPS.length);
    }, 3000);
    return () => clearInterval(interval);
  }, []);

  const togglePref = (label: string) => {
    setSelectedPrefs((prev) =>
      prev.includes(label) ? prev.filter((p) => p !== label) : [...prev, label]
    );
  };

  const toggleFilter = (tag: string) => {
    setActiveFilters((prev) =>
      prev.includes(tag) ? prev.filter((t) => t !== tag) : [...prev, tag]
    );
  };

  // Filter trips by search query + active tag filters
  const filteredTrips = TRENDING_TRIPS.filter((trip) => {
    const q = searchQuery.toLowerCase();
    const matchesSearch =
      !q ||
      trip.title.toLowerCase().includes(q) ||
      trip.destination.toLowerCase().includes(q) ||
      trip.tags.some((t) => t.toLowerCase().includes(q));
    const matchesTags =
      activeFilters.length === 0 ||
      trip.tags.some((t) => activeFilters.includes(t));
    return matchesSearch && matchesTags;
  });

  return (
    <div className="min-h-screen bg-background text-foreground overflow-x-hidden">
      {/* ── Ambient gradients ─────────────────────────────────────────── */}
      <div className="pointer-events-none fixed inset-0 -z-10 overflow-hidden">
        <div className="absolute -top-60 -left-60 h-[700px] w-[700px] rounded-full bg-trippy-300/30 blur-[120px]" />
        <div className="absolute top-[20%] right-[-10%] h-[600px] w-[600px] rounded-full bg-accent-300/25 blur-[100px]" />
        <div className="absolute bottom-[-5%] left-[30%] h-[500px] w-[500px] rounded-full bg-trippy-200/40 blur-[100px]" />
        <div className="absolute top-[60%] left-[-5%] h-[400px] w-[400px] rounded-full bg-accent-200/30 blur-[80px]" />
      </div>

      {/* ════════════════════════════════════════════════════════════════
          HEADER
          ════════════════════════════════════════════════════════════ */}
      <header className="glass-strong sticky top-0 z-50 px-4 lg:px-8">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between">
          <Logo size="md" />

          {/* Desktop nav */}
          <nav className="hidden md:flex items-center gap-8 text-sm font-medium text-muted">
            <a href="#discover" className="hover:text-foreground transition-colors">Discover</a>
            <a href="#ai-trips" className="hover:text-foreground transition-colors">AI Trips</a>
            <a href="#how-it-works" className="hover:text-foreground transition-colors">How It Works</a>
            <a href="#features" className="hover:text-foreground transition-colors">Features</a>
          </nav>

          <div className="flex items-center gap-3">
            <Link href="/login">
              <Button variant="ghost" size="sm">Log in</Button>
            </Link>
            <Link href="/register">
              <Button size="sm">Get Started</Button>
            </Link>
          </div>
        </div>
      </header>

      {/* ════════════════════════════════════════════════════════════════
          HERO
          ════════════════════════════════════════════════════════════ */}
      <section className="relative mx-auto flex max-w-7xl flex-col items-center px-4 pt-20 pb-8 text-center lg:pt-32">
        {/* Floating elements */}
        <motion.div
          className="absolute top-24 left-[8%] hidden lg:block"
          animate={{ y: [0, -12, 0] }}
          transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
        >
          <div className="glass-sm p-3 rounded-2xl">
            <Plane size={20} className="text-trippy-600" />
          </div>
        </motion.div>
        <motion.div
          className="absolute top-40 right-[10%] hidden lg:block"
          animate={{ y: [0, 10, 0] }}
          transition={{ duration: 5, repeat: Infinity, ease: "easeInOut" }}
        >
          <div className="glass-sm p-3 rounded-2xl">
            <Globe size={20} className="text-accent-600" />
          </div>
        </motion.div>
        <motion.div
          className="absolute top-64 left-[15%] hidden lg:block"
          animate={{ y: [0, -8, 0] }}
          transition={{ duration: 3.5, repeat: Infinity, ease: "easeInOut" }}
        >
          <div className="glass-sm p-3 rounded-2xl">
            <Heart size={18} className="text-danger" />
          </div>
        </motion.div>

        {/* Pill badge */}
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6 }}
          className="mb-6 inline-flex items-center gap-2 rounded-full bg-trippy-500/10 px-5 py-2 text-sm font-medium text-trippy-600 border border-trippy-500/20"
        >
          <Zap size={14} className="text-accent-600" />
          Powered by AI — Plan trips in seconds
        </motion.div>

        {/* Heading */}
        <motion.h1
          className="max-w-4xl text-4xl font-extrabold leading-[1.1] tracking-tight sm:text-6xl lg:text-7xl"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, delay: 0.1 }}
        >
          Explore the world,{" "}
          <br className="hidden sm:block" />
          <span className="text-trippy-600">
            together
          </span>
        </motion.h1>

        <motion.p
          className="mt-6 max-w-2xl text-lg text-muted leading-relaxed sm:text-xl"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.25 }}
        >
          Trippy is the AI-powered collaborative trip planner. Create
          itineraries in seconds, invite your crew, and turn dream
          destinations into real adventures.
        </motion.p>

        {/* ── Hero Search Bar ─────────────────────────────── */}
        <motion.div
          className={`mt-10 w-full transition-all duration-500 ${isSearchFocused ? "max-w-4xl scale-[1.01]" : "max-w-3xl hover:scale-[1.005]"}`}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.4 }}
        >
          <div className={`glass-strong p-2 flex flex-col sm:flex-row items-stretch gap-2 transition-all duration-500 rounded-2xl ${isSearchFocused ? "ring-4 ring-trippy-500/30 shadow-[0_0_60px_-15px_rgba(62,155,126,0.4)] bg-white/95" : "hover:ring-2 hover:ring-trippy-500/20 hover:shadow-xl"}`}>
            <div className="relative flex-1 flex items-center">
              <Search size={18} className="absolute left-4 text-muted" />
              <input
                type="text"
                value={searchQuery}
                onFocus={() => setIsSearchFocused(true)}
                onBlur={() => setIsSearchFocused(false)}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder={searchQuery ? "" : `Search trips — ${typedDestination}|`}
                className="w-full bg-transparent py-3.5 pl-12 pr-28 text-sm text-foreground placeholder:text-muted/70 outline-none"
              />
              <div className="absolute right-3 flex items-center gap-1 cursor-default pointer-events-none opacity-70">
                <Sparkles size={12} className="text-trippy-500" />
                <span className="text-[10px] font-medium text-trippy-500 uppercase tracking-widest hidden sm:inline">AI Powered</span>
              </div>
            </div>
            
            <Button variant="secondary" onClick={() => setShowAIBuilder(true)} className="sm:w-auto h-full shrink-0 group border border-trippy-500/20 hover:border-trippy-500/40">
              <Sparkles size={16} className="text-trippy-600 group-hover:text-trippy-500 transition-colors" />
              AI Trip
            </Button>
          </div>

          {/* Quick filter pills */}
          <div className="mt-4 flex flex-wrap justify-center gap-2 relative">
            {["Beach", "Mountains", "City Break", "Adventure", "Wellness", "Road Trip"].map(
              (tag) => {
                // Map filter labels to trip tag names where different
                const tagMap: Record<string, string> = { "City Break": "City", "Mountains": "Nature" };
                const mappedTag = tagMap[tag] ?? tag;
                const isActive = activeFilters.includes(mappedTag);
                return (
                  <button
                    key={tag}
                    onClick={() => toggleFilter(mappedTag)}
                    className={`glass-sm px-3 py-1.5 text-xs font-medium cursor-pointer transition-all ${
                      isActive
                        ? "!bg-trippy-500/15 !border-trippy-500/30 text-foreground"
                        : "text-muted hover:text-foreground hover:bg-surface-hover"
                    }`}
                  >
                    {tag}
                    {isActive && <span className="ml-1.5">✕</span>}
                  </button>
                );
              }
            )}

            {/* Dates Filter */}
            <button
              onClick={() => setShowDatePicker(!showDatePicker)}
              className={`glass-sm px-3 py-1.5 text-xs font-medium cursor-pointer transition-all ${
                startDate || endDate ? "!bg-trippy-500/15 !border-trippy-500/30 text-foreground" : "text-muted hover:text-foreground hover:bg-surface-hover"
              }`}
            >
              <Calendar size={12} className="inline mr-1.5 mb-0.5" />
              {startDate && endDate ? `${startDate.toLocaleDateString(undefined, {month:'short', day:'numeric'})} - ${endDate.toLocaleDateString(undefined, {month:'short', day:'numeric'})}` : "Add dates"}
            </button>
            
            <AnimatePresence>
              {showDatePicker && (
                <>
                  <div className="fixed inset-0 z-40" onClick={(e) => { e.stopPropagation(); setShowDatePicker(false); }} />
                  <motion.div
                    initial={{ opacity: 0, y: 10, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, y: 10, scale: 0.95 }}
                    className="absolute top-10 left-1/2 -translate-x-1/2 z-50 p-4 glass-strong rounded-2xl shadow-2xl border border-trippy-500/20 w-full max-w-lg flex flex-col sm:flex-row gap-4"
                  >
                    <MiniCalendar title="Start Date" date={startDate} setDate={setStartDate} />
                    <MiniCalendar title="End Date" date={endDate} setDate={setEndDate} />
                  </motion.div>
                </>
              )}
            </AnimatePresence>

            {(activeFilters.length > 0 || searchQuery || startDate || endDate) && (
              <button
                onClick={() => { setActiveFilters([]); setSearchQuery(""); setStartDate(null); setEndDate(null); }}
                className="px-3 py-1.5 text-xs font-medium text-danger cursor-pointer hover:underline"
              >
                Clear all
              </button>
            )}
          </div>
        </motion.div>

        {/* ── Hero Stats Row ──────────────────────────────── */}
        <AnimatePresence>
          {!isSearchActive && (
            <motion.div
              className="grid w-full max-w-3xl grid-cols-2 gap-4 sm:grid-cols-4 overflow-hidden"
              initial={{ height: 0, opacity: 0, marginTop: 0 }}
              animate={{ height: "auto", opacity: 1, marginTop: 56 }}
              exit={{ height: 0, opacity: 0, marginTop: 0 }}
              transition={{ duration: 0.5, ease: "easeInOut" }}
            >
              {STATS.map(({ value, label, icon: Icon }) => (
                <div key={label} className="glass-sm p-4 text-center group hover:bg-surface-hover transition-all cursor-default">
                  <Icon size={18} className="mx-auto mb-2 text-trippy-600 group-hover:text-trippy-300 transition-colors" />
                  <div className="text-2xl font-bold text-trippy-600">
                    {value}
                  </div>
                  <div className="text-xs text-muted mt-0.5">{label}</div>
                </div>
              ))}
            </motion.div>
          )}
        </AnimatePresence>
      </section>

      {/* ════════════════════════════════════════════════════════════════
          DISCOVER & JOIN TRIPS
          ════════════════════════════════════════════════════════════ */}
      <section id="discover" className={`mx-auto max-w-7xl px-4 lg:px-8 transition-all duration-500 ${isSearchActive ? "py-10" : "py-20"}`}>
        <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between mb-10">
          <div>
            {!isSearchActive ? (
              <motion.div
                initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}
                className="flex flex-col items-start"
              >
                <div className="inline-flex items-center gap-2 rounded-full bg-accent-400/10 px-4 py-1.5 text-xs font-semibold text-accent-600 mb-3">
                  <TrendingUp size={12} /> TRENDING NOW
                </div>
                <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                  Discover <span className="text-trippy-600">amazing trips</span>
                </h2>
                <p className="mt-2 text-muted max-w-lg">
                  Browse curated trips from travelers & AI. Find your perfect adventure and join with one click.
                </p>
              </motion.div>
            ) : (
              <motion.div
                initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}
                className="flex flex-col items-start"
              >
                <div className="inline-flex items-center gap-2 rounded-full bg-trippy-500/10 px-4 py-1.5 text-xs font-semibold text-trippy-600 mb-3">
                  <Search size={12} /> SEARCH RESULTS
                </div>
                <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
                  Found <span className="text-trippy-600">{filteredTrips.length} trips</span>
                </h2>
                <p className="mt-2 text-muted max-w-lg">
                  Showing trips matching your active searches and filters.
                </p>
              </motion.div>
            )}
          </div>
          <Link href="/register" className="mt-4 sm:mt-0">
            <Button variant="secondary" size="sm">
              View all trips <ArrowRight size={14} />
            </Button>
          </Link>
        </div>

        {/* Trip Cards Grid */}
        <AnimatePresence mode="popLayout">
          {filteredTrips.length > 0 ? (
            <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
              {filteredTrips.map((trip, i) => (
            <motion.div
              key={trip.id}
              custom={i}
              variants={fadeUp}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              onMouseEnter={() => setHoveredTrip(trip.id)}
              onMouseLeave={() => setHoveredTrip(null)}
            >
              <GlassCard className="p-0 overflow-hidden group cursor-pointer hover:shadow-xl hover:shadow-trippy-500/10 transition-all duration-500">
                {/* Image */}
                <div className="relative h-48 overflow-hidden">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={trip.image}
                    alt={trip.title}
                    className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-black/20 to-transparent" />

                  {/* Top row */}
                  <div className="absolute top-3 left-3 right-3 flex items-start justify-between">
                    <div className="flex gap-1.5">
                      {trip.tags.map((tag) => (
                        <Badge key={tag} variant="default" className="bg-black/40 text-white border-0 backdrop-blur-sm text-[10px]">
                          {tag}
                        </Badge>
                      ))}
                    </div>
                    {trip.isAI && (
                      <div className="flex items-center gap-1 rounded-full bg-trippy-500/80 backdrop-blur-sm px-2.5 py-1 text-[10px] font-semibold text-white">
                        <Sparkles size={10} /> AI Created
                      </div>
                    )}
                  </div>

                  {/* Bottom price */}
                  <div className="absolute bottom-3 right-3 glass-sm px-3 py-1.5 !rounded-lg bg-black/40 border-0 backdrop-blur-md">
                    <span className="text-sm font-bold text-white">{trip.price}</span>
                    <span className="text-[10px] text-white/70 ml-1">/person</span>
                  </div>
                </div>

                {/* Content */}
                <div className="p-4 space-y-3">
                  <div className="flex items-start justify-between gap-2">
                    <h3 className="text-base font-semibold leading-tight line-clamp-1 group-hover:text-trippy-600 transition-colors">
                      {trip.title}
                    </h3>
                    <div className="flex items-center gap-1 text-xs text-accent-600 shrink-0">
                      <Star size={12} fill="currentColor" />
                      {trip.rating}
                    </div>
                  </div>

                  <div className="flex items-center gap-1.5 text-sm text-muted">
                    <MapPin size={14} className="shrink-0 text-trippy-600" />
                    <span className="line-clamp-1">{trip.destination}</span>
                  </div>

                  <div className="flex items-center gap-1.5 text-sm text-muted">
                    <Calendar size={14} className="shrink-0 text-trippy-600" />
                    <span>{trip.dates}</span>
                  </div>

                  {/* Footer */}
                  <div className="flex items-center justify-between pt-3 border-t border-border">
                    <div className="flex items-center gap-2">
                      <Avatar size="sm" name={trip.creator.name} />
                      <div className="text-xs">
                        <div className="font-medium">{trip.creator.name}</div>
                        <div className="text-muted">{trip.reviews} reviews</div>
                      </div>
                    </div>

                    {/* Spots left */}
                    <div className="flex items-center gap-2">
                      <div className="h-1.5 w-16 rounded-full bg-border overflow-hidden">
                        <div
                          className="h-full rounded-full bg-trippy-gradient"
                          style={{
                            width: `${((trip.maxSpots - trip.spots) / trip.maxSpots) * 100}%`,
                          }}
                        />
                      </div>
                      <span className="text-xs text-muted whitespace-nowrap">
                        {trip.spots} left
                      </span>
                    </div>
                  </div>

                  {/* Hover reveal: join button */}
                  <AnimatePresence>
                    {hoveredTrip === trip.id && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: "auto" }}
                        exit={{ opacity: 0, height: 0 }}
                        transition={{ duration: 0.2 }}
                        className="overflow-hidden"
                      >
                        <Button className="w-full mt-1" size="sm">
                          Join this trip <ArrowRight size={14} />
                        </Button>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              </GlassCard>
            </motion.div>
          ))}
            </div>
          ) : (
            <motion.div
              key="no-results"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="text-center py-16"
            >
              <div className="mx-auto mb-4 w-16 h-16 rounded-2xl bg-trippy-500/10 flex items-center justify-center">
                <Search size={28} className="text-trippy-600" />
              </div>
              <h3 className="text-lg font-semibold">No trips found</h3>
              <p className="mt-2 text-muted max-w-md mx-auto">
                No trips match &ldquo;{searchQuery || activeFilters.join(", ")}&rdquo;. Try a different search or{" "}
                <button onClick={() => setShowAIBuilder(true)} className="text-trippy-600 font-medium hover:underline cursor-pointer">
                  let AI create one for you
                </button>.
              </p>
              <div className="mt-4 flex justify-center gap-3">
                <Button variant="secondary" size="sm" onClick={() => { setSearchQuery(""); setActiveFilters([]); }}>
                  Clear filters
                </Button>
                <Button size="sm" onClick={() => setShowAIBuilder(true)}>
                  <Sparkles size={14} /> AI Trip Builder
                </Button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </section>

      {/* ════════════════════════════════════════════════════════════════
          AI TRIP CREATION SHOWCASE
          ════════════════════════════════════════════════════════════ */}
      <section id="ai-trips" className="relative overflow-hidden py-24">
        {/* Section glow */}
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-[500px] w-[500px] rounded-full bg-trippy-300/30 blur-[120px]" />
        </div>

        <div className="relative mx-auto max-w-7xl px-4 lg:px-8">
          <div className="text-center mb-16">
            <motion.div
              initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}
              className="inline-flex items-center gap-2 rounded-full bg-trippy-500/10 px-4 py-1.5 text-xs font-semibold text-trippy-600 mb-3 border border-trippy-500/20"
            >
              <Sparkles size={12} /> AI-POWERED
            </motion.div>
            <motion.h2
              className="text-3xl font-bold tracking-tight sm:text-4xl"
              initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.5 }}
            >
              Let AI plan your{" "}
              <span className="text-trippy-600">
                dream trip
              </span>
            </motion.h2>
            <p className="mt-3 text-muted max-w-xl mx-auto text-lg">
              Just tell us where and when. Our AI does the rest — creating personalised itineraries in seconds.
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-10 items-center">
            {/* Left: AI Mock Interface */}
            <motion.div
              initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.6 }}
            >
              <GlassCard variant="strong" className="p-0 overflow-hidden">
                {/* Mock header bar */}
                <div className="flex items-center gap-2 px-5 py-3 border-b border-border">
                  <div className="flex gap-1.5">
                    <div className="w-3 h-3 rounded-full bg-danger/60" />
                    <div className="w-3 h-3 rounded-full bg-warning/60" />
                    <div className="w-3 h-3 rounded-full bg-success/60" />
                  </div>
                  <div className="flex-1 flex justify-center">
                    <span className="text-xs text-muted font-medium">Trippy AI Trip Builder</span>
                  </div>
                </div>

                <div className="p-6 space-y-4">
                  {/* User message */}
                  <div className="flex justify-end">
                    <div className="glass-sm px-4 py-2.5 max-w-[80%] text-sm">
                      Plan me a 10-day trip to Japan with my 3 friends. We love food, temples, and nightlife. Budget around $3000 each. 🇯🇵
                    </div>
                  </div>

                  {/* AI typing */}
                  <div className="flex gap-3">
                    <div className="shrink-0 w-8 h-8 rounded-full bg-trippy-500 flex items-center justify-center">
                      <Sparkles size={14} className="text-white" />
                    </div>
                    <div className="glass-sm px-4 py-3 max-w-[85%] text-sm space-y-2">
                      <p className="font-medium text-foreground">Here&apos;s your 10-day Japan itinerary! 🎌</p>
                      <div className="space-y-1.5 text-muted text-xs">
                        <div className="flex items-center gap-2">
                          <div className="w-1.5 h-1.5 rounded-full bg-trippy-400" />
                          Days 1-3: Tokyo — Shibuya, Akihabara, Tsukiji market
                        </div>
                        <div className="flex items-center gap-2">
                          <div className="w-1.5 h-1.5 rounded-full bg-trippy-400" />
                          Days 4-5: Hakone — Mt. Fuji views, hot springs
                        </div>
                        <div className="flex items-center gap-2">
                          <div className="w-1.5 h-1.5 rounded-full bg-trippy-400" />
                          Days 6-8: Kyoto — Fushimi Inari, bamboo grove, tea ceremony
                        </div>
                        <div className="flex items-center gap-2">
                          <div className="w-1.5 h-1.5 rounded-full bg-trippy-400" />
                          Days 9-10: Osaka — Dotonbori, street food tour, nightlife
                        </div>
                      </div>
                      <div className="flex items-center gap-3 pt-2 text-xs">
                        <span className="flex items-center gap-1 text-success"><Clock size={10} /> 10 days</span>
                        <span className="flex items-center gap-1 text-trippy-600"><Users size={10} /> 4 travelers</span>
                        <span className="flex items-center gap-1 text-accent-600"><TrendingUp size={10} /> ~$2,840/person</span>
                      </div>
                    </div>
                  </div>

                  {/* CTA */}
                  <div className="pt-2 flex gap-3">
                    <Button className="w-full flex-1" size="sm" onClick={() => setShowAIBuilder(true)}>
                        <Sparkles size={14} /> Generate my trip
                    </Button>
                    <Button variant="secondary" size="sm">Customize</Button>
                  </div>
                </div>
              </GlassCard>
            </motion.div>

            {/* Right: How AI works steps */}
            <motion.div
              className="space-y-6"
              initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }} transition={{ duration: 0.6, delay: 0.2 }}
            >
              <h3 className="text-xl font-bold">Create a trip in 4 steps</h3>
              <div className="space-y-3">
                {AI_STEPS.map((step, i) => {
                  const StepIcon = step.icon;
                  const isActive = activeAIStep === i;
                  return (
                    <motion.div
                      key={step.label}
                      className={`glass-sm p-4 flex items-center gap-4 cursor-pointer transition-all duration-300 ${
                        isActive ? "!bg-trippy-500/10 !border-trippy-500/30 shadow-lg shadow-trippy-500/5" : "hover:bg-surface-hover"
                      }`}
                      onClick={() => setActiveAIStep(i)}
                      animate={isActive ? { scale: 1.02 } : { scale: 1 }}
                    >
                      <div className={`shrink-0 w-10 h-10 rounded-xl flex items-center justify-center transition-colors ${
                        isActive ? "bg-trippy-gradient text-white" : "bg-trippy-500/10 text-trippy-600"
                      }`}>
                        <StepIcon size={18} />
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="text-xs text-muted font-medium">Step {i + 1}</span>
                          {isActive && (
                            <motion.div
                              layoutId="activeStep"
                              className="h-1 w-6 rounded-full bg-trippy-gradient"
                            />
                          )}
                        </div>
                        <div className="font-semibold text-sm mt-0.5">{step.label}</div>
                        <div className="text-xs text-muted mt-0.5">{step.desc}</div>
                      </div>
                      <ChevronRight size={16} className={`text-muted transition-transform ${isActive ? "translate-x-1 text-trippy-600" : ""}`} />
                    </motion.div>
                  );
                })}
              </div>

              <Button size="lg" className="mt-4 bg-trippy-600 hover:shadow-trippy-500/25" onClick={() => setShowAIBuilder(true)}>
                  <Sparkles size={16} /> Try AI Trip Builder <ArrowRight size={16} />
              </Button>
            </motion.div>
          </div>
        </div>
      </section>

      {/* ════════════════════════════════════════════════════════════════
          PERSONALISATION SECTION
          ════════════════════════════════════════════════════════════ */}
      <section className="mx-auto max-w-7xl px-4 py-20 lg:px-8">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Left: Text + Preference Chips */}
          <motion.div
            initial={{ opacity: 0, x: -20 }} whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }} transition={{ duration: 0.5 }}
          >
            <div className="inline-flex items-center gap-2 rounded-full bg-success/10 px-4 py-1.5 text-xs font-semibold text-success mb-3">
              <Heart size={12} /> PERSONALISED FOR YOU
            </div>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
              Trips that match{" "}
              <span className="text-trippy-600">your style</span>
            </h2>
            <p className="mt-3 text-muted max-w-lg text-lg">
              Select your travel preferences and we&apos;ll curate trips, destinations, and
              activities that match exactly what you&apos;re looking for.
            </p>

            {/* Preference chips */}
            <div className="mt-8 flex flex-wrap gap-3">
              {PREFERENCES.map(({ icon: PIcon, label, color }) => {
                const isSelected = selectedPrefs.includes(label);
                return (
                  <button
                    key={label}
                    onClick={() => togglePref(label)}
                    className={`glass-sm px-4 py-2.5 flex items-center gap-2 text-sm font-medium transition-all duration-200 cursor-pointer ${
                      isSelected
                        ? "!bg-trippy-500/15 !border-trippy-500/30 text-foreground shadow-md"
                        : "text-muted hover:text-foreground hover:bg-surface-hover"
                    }`}
                  >
                    <PIcon size={16} className={isSelected ? color : "text-muted"} />
                    {label}
                    {isSelected && <span className="w-2 h-2 rounded-full bg-trippy-gradient ml-1" />}
                  </button>
                );
              })}
            </div>

            <p className="mt-5 text-xs text-muted">
              {selectedPrefs.length > 0
                ? `Showing trips for: ${selectedPrefs.join(", ")}`
                : "Select preferences to personalise your feed"}
            </p>
          </motion.div>

          {/* Right: Mock personalised feed */}
          <motion.div
            className="space-y-4"
            initial={{ opacity: 0, x: 20 }} whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }} transition={{ duration: 0.5, delay: 0.2 }}
          >
            {[
              {
                title: "Maldives Overwater Paradise",
                dest: "Maldives",
                weather: "29°C Sunny",
                match: 98,
                tags: ["Beach", "Luxury"],
              },
              {
                title: "Swiss Alps Winter Trek",
                dest: "Zermatt, Switzerland",
                weather: "2°C Snowy",
                match: 85,
                tags: ["Mountains", "Adventure"],
              },
              {
                title: "Costa Rica Rainforest",
                dest: "San José, Costa Rica",
                weather: "26°C Tropical",
                match: 92,
                tags: ["Nature", "Adventure"],
              },
            ].map((item, i) => (
              <motion.div
                key={item.title}
                initial={{ opacity: 0, y: 15 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 + 0.3 }}
              >
                <div className="glass p-4 flex items-center gap-4 hover:bg-surface-hover transition-all cursor-pointer group">
                  {/* Match score */}
                  <div className="shrink-0 w-14 h-14 rounded-xl bg-trippy-gradient flex flex-col items-center justify-center">
                    <span className="text-lg font-bold text-white leading-none">{item.match}%</span>
                    <span className="text-[8px] text-white/70 font-medium">match</span>
                  </div>

                  <div className="flex-1 min-w-0">
                    <h4 className="font-semibold text-sm group-hover:text-trippy-600 transition-colors line-clamp-1">
                      {item.title}
                    </h4>
                    <div className="flex items-center gap-3 mt-1 text-xs text-muted">
                      <span className="flex items-center gap-1">
                        <MapPin size={10} /> {item.dest}
                      </span>
                      <span className="flex items-center gap-1">
                        <CloudSun size={10} /> {item.weather}
                      </span>
                    </div>
                    <div className="flex gap-1.5 mt-1.5">
                      {item.tags.map((t) => (
                        <Badge key={t} className="text-[9px] py-0">{t}</Badge>
                      ))}
                    </div>
                  </div>

                  <ChevronRight size={16} className="text-muted group-hover:text-trippy-600 group-hover:translate-x-1 transition-all" />
                </div>
              </motion.div>
            ))}

            <div className="text-center pt-2">
              <Link href="/register">
                <Button variant="ghost" size="sm">
                  See all personalised picks <ArrowRight size={14} />
                </Button>
              </Link>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ════════════════════════════════════════════════════════════════
          HOW IT WORKS
          ════════════════════════════════════════════════════════════ */}
      <section id="how-it-works" className="relative py-24 overflow-hidden">
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute top-0 left-1/2 -translate-x-1/2 h-px w-full max-w-7xl bg-gradient-to-r from-transparent via-border to-transparent" />
        </div>
        <div className="mx-auto max-w-7xl px-4 lg:px-8 text-center">
          <motion.h2
            className="text-3xl font-bold tracking-tight sm:text-4xl"
            initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }} transition={{ duration: 0.5 }}
          >
            How Trippy{" "}
            <span className="text-trippy-600">works</span>
          </motion.h2>
          <p className="mt-3 text-muted text-lg max-w-xl mx-auto">
            From idea to adventure in minutes — not hours.
          </p>

          <div className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {[
              { num: "01", icon: Search, title: "Search or AI-Create", desc: "Find existing trips or let AI build one from scratch based on your preferences." },
              { num: "02", icon: Users, title: "Build your crew", desc: "Invite friends via link. Everyone collaborates on the plan in real-time." },
              { num: "03", icon: Calendar, title: "Plan day-by-day", desc: "Add activities, set budgets, vote on options. AI fills gaps for you." },
              { num: "04", icon: Plane, title: "Travel & share", desc: "Get real-time updates, chat with your group, and share memories." },
            ].map((step, i) => (
              <motion.div
                key={step.num}
                custom={i}
                variants={fadeUp}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
              >
                <GlassCard className="text-center h-full hover:bg-surface-hover transition-all group">
                  <div className="text-xs font-bold text-trippy-600/50 mb-3">{step.num}</div>
                  <div className="mx-auto mb-4 w-14 h-14 rounded-2xl bg-trippy-500/10 flex items-center justify-center group-hover:bg-trippy-500/20 transition-colors">
                    <step.icon size={24} className="text-trippy-600" />
                  </div>
                  <h3 className="font-semibold text-sm">{step.title}</h3>
                  <p className="mt-2 text-xs text-muted leading-relaxed">{step.desc}</p>
                </GlassCard>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ════════════════════════════════════════════════════════════════
          FEATURES GRID
          ════════════════════════════════════════════════════════════ */}
      <section id="features" className="mx-auto max-w-7xl px-4 py-20 lg:px-8">
        <div className="mb-14 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Everything you need for{" "}
            <span className="text-trippy-600">epic trips</span>
          </h2>
          <p className="mt-4 text-muted text-lg">
            From brainstorming to boarding — Trippy has it covered.
          </p>
        </div>

        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map(({ icon: Icon, title, desc }, i) => (
            <motion.div
              key={title}
              custom={i}
              variants={fadeUp}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
            >
              <GlassCard className="h-full hover:bg-surface-hover transition-all duration-300 group">
                <div className="mb-4 inline-flex rounded-xl bg-trippy-500/10 p-3 text-trippy-600 group-hover:bg-trippy-500/20 group-hover:scale-110 transition-all">
                  <Icon size={22} />
                </div>
                <h3 className="text-lg font-semibold">{title}</h3>
                <p className="mt-2 text-sm text-muted leading-relaxed">{desc}</p>
              </GlassCard>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ════════════════════════════════════════════════════════════════
          TESTIMONIALS
          ════════════════════════════════════════════════════════════ */}
      <section className="mx-auto max-w-7xl px-4 py-20 lg:px-8">
        <div className="text-center mb-14">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Loved by{" "}
            <span className="text-trippy-600">travelers</span>
          </h2>
          <p className="mt-3 text-muted text-lg">Don&apos;t take our word for it.</p>
        </div>

        <motion.div
          className="grid gap-6 md:grid-cols-3"
          variants={staggerContainer}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
        >
          {TESTIMONIALS.map((t) => (
            <motion.div key={t.name} variants={fadeIn}>
              <GlassCard className="h-full hover:bg-surface-hover transition-all">
                {/* Stars */}
                <div className="flex gap-1 mb-4">
                  {Array.from({ length: t.rating }).map((_, j) => (
                    <Star key={j} size={14} className="text-accent-600" fill="currentColor" />
                  ))}
                </div>
                <p className="text-sm leading-relaxed text-foreground/90 italic">
                  &ldquo;{t.text}&rdquo;
                </p>
                <div className="flex items-center gap-3 mt-5 pt-4 border-t border-border">
                  <Avatar size="sm" name={t.name} />
                  <div>
                    <div className="text-sm font-semibold">{t.name}</div>
                    <div className="text-xs text-muted">{t.role}</div>
                  </div>
                </div>
              </GlassCard>
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* ════════════════════════════════════════════════════════════════
          FINAL CTA
          ════════════════════════════════════════════════════════════ */}
      <section className="mx-auto max-w-7xl px-4 py-20 lg:px-8">
        <GlassCard variant="strong" className="relative py-20 overflow-hidden text-center">
          {/* Inner glow */}
          <div className="pointer-events-none absolute inset-0">
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[400px] h-[400px] rounded-full bg-accent-300/30 blur-[80px]" />
          </div>

          <motion.div
            className="relative"
            initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }} transition={{ duration: 0.6 }}
          >
            <div className="mx-auto mb-6 w-16 h-16 rounded-2xl bg-trippy-gradient flex items-center justify-center">
              <Compass size={28} className="text-white" />
            </div>
            <h2 className="text-3xl font-bold tracking-tight sm:text-4xl lg:text-5xl">
              Ready to explore the world?
            </h2>
            <p className="mx-auto mt-4 max-w-lg text-muted text-lg">
              Join 120,000+ travelers planning smarter trips. Your next adventure is one click away.
            </p>
            <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link href="/register">
                <Button size="lg">
                  Start for free <ArrowRight size={16} />
                </Button>
              </Link>
              <Button variant="secondary" size="lg" onClick={() => setShowAIBuilder(true)}>
                  <Sparkles size={16} /> Try AI Trip Builder
              </Button>
            </div>
            <p className="mt-4 text-xs text-muted flex items-center justify-center gap-2">
              <Shield size={12} /> No credit card required &middot; Free forever for personal use
            </p>
          </motion.div>
        </GlassCard>
      </section>

      {/* ════════════════════════════════════════════════════════════════
          FOOTER
          ════════════════════════════════════════════════════════════ */}
      <footer className="border-t border-border px-4 py-12 lg:px-8">
        <div className="mx-auto max-w-7xl">
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4 mb-10">
            <div>
              <Logo size="md" />
              <p className="mt-3 text-sm text-muted max-w-xs leading-relaxed">
                The AI-powered trip planner that brings your travel dreams to life.
              </p>
            </div>
            <div>
              <h4 className="font-semibold text-sm mb-3">Product</h4>
              <ul className="space-y-2 text-sm text-muted">
                <li className="hover:text-foreground cursor-pointer transition-colors">Features</li>
                <li className="hover:text-foreground cursor-pointer transition-colors">AI Trip Builder</li>
                <li className="hover:text-foreground cursor-pointer transition-colors">Pricing</li>
                <li className="hover:text-foreground cursor-pointer transition-colors">Mobile App</li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold text-sm mb-3">Company</h4>
              <ul className="space-y-2 text-sm text-muted">
                <li className="hover:text-foreground cursor-pointer transition-colors">About</li>
                <li className="hover:text-foreground cursor-pointer transition-colors">Blog</li>
                <li className="hover:text-foreground cursor-pointer transition-colors">Careers</li>
                <li className="hover:text-foreground cursor-pointer transition-colors">Contact</li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold text-sm mb-3">Legal</h4>
              <ul className="space-y-2 text-sm text-muted">
                <li className="hover:text-foreground cursor-pointer transition-colors">Privacy Policy</li>
                <li className="hover:text-foreground cursor-pointer transition-colors">Terms of Service</li>
                <li className="hover:text-foreground cursor-pointer transition-colors">Cookie Policy</li>
              </ul>
            </div>
          </div>
          <div className="border-t border-border pt-6 flex flex-col sm:flex-row items-center justify-between gap-3 text-sm text-muted">
            <span>&copy; {new Date().getFullYear()} Trippy. All rights reserved.</span>
            <span>Made with <Heart size={12} className="inline text-danger" fill="currentColor" /> for travelers everywhere.</span>
          </div>
        </div>
      </footer>

      {/* AI Trip Builder Modal */}
      <AITripBuilderModal open={showAIBuilder} onClose={() => setShowAIBuilder(false)} />
    </div>
  );
}
