spring:
  config:
    import: "optional:file:../../infra/docker/.env[.properties]"
  application:
    name: trip-service
  devtools:
    livereload:
      enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5434}/${POSTGRES_DB:trippy_db}?currentSchema=trip_schema
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: TripServicePool
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: trip_schema
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST:trippy}

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: WARN
    pse.trippy.tripservice: INFO
    org.hibernate: ERROR
    org.hibernate.SQL: WARN
    org.hibernate.engine: ERROR
    org.hibernate.orm: ERROR
    org.hibernate.type.descriptor.sql: WARN
    com.zaxxer.hikari: WARN
    org.springframework.boot: INFO
    org.springframework.web: WARN
    org.springframework.data: WARN
    org.springframework.orm: WARN
    org.springframework.amqp: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) [trip-service] %cyan(%logger{20}) — %msg%n"
