"use client";

import React, { useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  MapPin, Calendar, Users, Sparkles, Loader2, Check,
  DollarSign, Send, ArrowRightLeft, Plus, Trash2,
  Lightbulb, Undo2, ChevronDown, ChevronUp, Pencil,
  Bus, Clock, ArrowLeft,
} from "lucide-react";
import Logo from "@/components/Logo";
import AmbientBackground from "@/components/layout/AmbientBackground";
import Button from "@/components/ui/Button";
import { getAccessToken } from "@/lib/api";

/* ── Types ─────────────────────────────────────────────────────────── */
interface AiItineraryDay {
  dayNumber: number;
  date?: string;
  title: string;
  weather?: WeatherSummary;
  transportRecommendations?: TransportRecommendation[];
  activities: AiItineraryActivity[];
}

interface WeatherSummary {
  condition?: string;
  temperatureCelsius?: number | null;
  advice?: string;
}

interface TransportRecommendation {
  from?: string;
  to?: string;
  mode?: string;
  estimatedDuration?: string;
  notes?: string;
}

interface AiItineraryActivity {
  time?: string;
  duration?: number;
  durationMinutes?: number;
  title: string;
  description?: string;
  location?: string;
  googleMapsUrl?: string;
  category?: string;
  estimatedCost?: string;
  tips?: string;
  bookingRequired?: boolean;
  lat?: number;
  lng?: number;
}

interface GeneratedTrip {
  title: string;
  destination: string;
  duration: string;
  budget: string;
  groupSize: string;
  rating: number;
  highlights: string[];
  reason: string;
  bestTimeToVisit: string;
  image: string;
  googleMapsUrl?: string;
  aiItinerary?: AiItineraryDay[];
}

interface ChatChange {
  type: string;
  dayNumber?: number;
  removed?: string;
  added?: string;
  summary: string;
}

interface ChatMsg {
  role: "user" | "assistant";
  content: string;
  changes?: ChatChange[];
  hasModification?: boolean;
}

interface TripFullScreenViewProps {
  trip: GeneratedTrip;
  userPrompt?: string;
  userDates?: { start: string; end?: string };
  onClose: () => void;
  onSave: () => void;
  saved: boolean;
}

const CAT_COLORS: Record<string, string> = {
  FOOD: "bg-orange-100 text-orange-700 border-orange-200",
  SIGHTSEEING: "bg-blue-100 text-blue-700 border-blue-200",
  TRANSPORT: "bg-slate-100 text-slate-600 border-slate-200",
  SHOPPING: "bg-pink-100 text-pink-700 border-pink-200",
  CULTURE: "bg-purple-100 text-purple-700 border-purple-200",
  NIGHTLIFE: "bg-indigo-100 text-indigo-700 border-indigo-200",
  NATURE: "bg-green-100 text-green-700 border-green-200",
  WELLNESS: "bg-teal-100 text-teal-700 border-teal-200",
};

const CAT_ICONS: Record<string, string> = {
  FOOD: "🍽️", SIGHTSEEING: "👁️", TRANSPORT: "🚌", SHOPPING: "🛍️",
  CULTURE: "🏛️", NIGHTLIFE: "🌙", NATURE: "🌿", WELLNESS: "🧘",
};

/* ── Main Component ────────────────────────────────────────────────── */
export default function TripFullScreenView({
  trip, userPrompt, userDates, onClose, onSave, saved,
}: TripFullScreenViewProps) {
  const [draftTrip, setDraftTrip] = useState<GeneratedTrip>(trip);
  const [itineraryVersion, setItineraryVersion] = useState(0);
  const [itineraryLoading, setItineraryLoading] = useState(false);
  const [itineraryError, setItineraryError] = useState("");
  const [chatMessages, setChatMessages] = useState<ChatMsg[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [chatLoading, setChatLoading] = useState(false);
  const [prevItinerary, setPrevItinerary] = useState<AiItineraryDay[] | null>(null);
  const [expandedDays, setExpandedDays] = useState<Set<number>>(new Set([1]));
  const chatEndRef = useRef<HTMLDivElement>(null);
  const autoGenerated = useRef(false);

  /* ── Edit State ─────────────────────────────────────────────────── */
  const [editingDayNum, setEditingDayNum] = useState<number | null>(null);
  const [editDayTitle, setEditDayTitle] = useState("");
  const [editingActivity, setEditingActivity] = useState<{ dayNumber: number; idx: number } | null>(null);
  const [editActivityForm, setEditActivityForm] = useState({
    title: "", description: "", time: "", location: "", estimatedCost: "",
  });

  // Converts "HH:MM" (24h, from <input type="time">) or "H:MM AM/PM" to minutes for sorting
  function timeToMinutes(t: string): number {
    if (!t) return Infinity;
    const m24 = t.match(/^(\d{1,2}):(\d{2})$/);
    if (m24) return parseInt(m24[1]) * 60 + parseInt(m24[2]);
    const m12 = t.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);
    if (m12) {
      let h = parseInt(m12[1]);
      const min = parseInt(m12[2]);
      if (m12[3].toUpperCase() === "PM" && h !== 12) h += 12;
      if (m12[3].toUpperCase() === "AM" && h === 12) h = 0;
      return h * 60 + min;
    }
    return Infinity;
  }

  useEffect(() => { setDraftTrip(trip); }, [trip]);

  // Fetch city image
  useEffect(() => {
    if (!trip.destination) return;
    let cancelled = false;
    fetch(`/api/images/city?q=${encodeURIComponent(trip.destination)}`)
      .then(r => r.json())
      .then(d => { if (!cancelled && d?.image) setDraftTrip(prev => ({ ...prev, image: d.image })); })
      .catch(() => {});
    return () => { cancelled = true; };
  }, [trip.destination]);

  // Auto-generate itinerary
  useEffect(() => {
    if (!autoGenerated.current && !draftTrip.aiItinerary?.length) {
      autoGenerated.current = true;
      void generateItinerary();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function generateItinerary() {
    if (!userDates?.start) {
      setItineraryError("Select travel dates before generating an itinerary.");
      return;
    }
    const effectiveEndDate = userDates.end || userDates.start;
    setItineraryLoading(true);
    setItineraryError("");
    try {
      const res = await fetch("/api/ai/itineraries", {
        method: "POST",
        headers: aiRequestHeaders(),
        body: JSON.stringify({
          constraints: {
            destination: draftTrip.destination,
            startDate: userDates.start,
            endDate: effectiveEndDate,
            budgetLevel: "MODERATE",
            adults: parseInt(draftTrip.groupSize) || 2,
            children: 0,
          },
          userPrompt: userPrompt
            ? `${userPrompt}. Highlights: ${draftTrip.highlights.join(", ")}`
            : `Highlights: ${draftTrip.highlights.join(", ")}`,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data?.error || "Failed");
      if (data.dailyPlan?.length) {
        setDraftTrip(prev => ({ ...prev, aiItinerary: data.dailyPlan }));
        setExpandedDays(new Set([1]));
      }
    } catch (err) {
      const message = err instanceof Error ? err.message : "Itinerary details are unavailable right now.";
      setItineraryError(message);
    }
    finally { setItineraryLoading(false); }
  }

  function toggleDay(day: number) {
    setExpandedDays(prev => {
      const next = new Set(prev);
      if (next.has(day)) {
        next.delete(day);
      } else {
        next.add(day);
      }
      return next;
    });
  }

  /* ── Edit Functions ─────────────────────────────────────────────── */
  function startEditDay(dayNum: number, currentTitle: string) {
    setEditingDayNum(dayNum);
    setEditDayTitle(currentTitle);
    setEditingActivity(null);
    if (!expandedDays.has(dayNum)) toggleDay(dayNum);
  }

  function saveEditDay() {
    if (!editingDayNum) return;
    if (editDayTitle.trim()) {
      setDraftTrip(prev => ({
        ...prev,
        aiItinerary: prev.aiItinerary?.map(d =>
          d.dayNumber === editingDayNum ? { ...d, title: editDayTitle } : d
        ),
      }));
    }
    setEditingDayNum(null);
  }

  function deleteActivity(dayNumber: number, idx: number) {
    setDraftTrip(prev => ({
      ...prev,
      aiItinerary: prev.aiItinerary?.map(d =>
        d.dayNumber === dayNumber
          ? { ...d, activities: d.activities.filter((_, i) => i !== idx) }
          : d
      ),
    }));
  }

  function startEditActivity(dayNumber: number, idx: number, act: AiItineraryDay["activities"][0]) {
    setEditingActivity({ dayNumber, idx });
    setEditActivityForm({
      title: act.title || "",
      description: act.description || "",
      time: act.time || "",
      location: act.location || "",
      estimatedCost: act.estimatedCost || "",
    });
    setEditingDayNum(null);
  }

  function saveEditActivity() {
    if (!editingActivity) return;
    const { dayNumber, idx } = editingActivity;
    setDraftTrip(prev => ({
      ...prev,
      aiItinerary: prev.aiItinerary?.map(d => {
        if (d.dayNumber !== dayNumber) return d;
        const updated = d.activities.map((a, i) =>
          i === idx ? { ...a, ...editActivityForm } : a
        );
        // Sort by time so the new/edited activity lands in chronological position
        updated.sort((a, b) => timeToMinutes(a.time || "") - timeToMinutes(b.time || ""));
        return { ...d, activities: updated };
      }),
    }));
    setEditingActivity(null);
  }

  function addActivity(dayNumber: number) {
    const day = draftTrip.aiItinerary?.find(d => d.dayNumber === dayNumber);
    const newIdx = day ? day.activities.length : 0;
    setDraftTrip(prev => ({
      ...prev,
      aiItinerary: prev.aiItinerary?.map(d =>
        d.dayNumber === dayNumber
          ? { ...d, activities: [...d.activities, { time: "", title: "New Activity", description: "", location: "", estimatedCost: "" }] }
          : d
      ),
    }));
    setEditingActivity({ dayNumber, idx: newIdx });
    setEditActivityForm({ title: "", description: "", time: "", location: "", estimatedCost: "" });
    setEditingDayNum(null);
  }

  async function handleChatSend(inputOverride?: string) {
    const text = inputOverride || chatInput.trim();
    if (!text || chatLoading) return;
    const newMsg: ChatMsg = { role: "user", content: text };
    const updated = [...chatMessages, newMsg];
    setChatMessages(updated);
    setChatInput("");
    setChatLoading(true);
    try {
      const res = await fetch("/api/ai/chat", {
        method: "POST",
        headers: aiRequestHeaders(),
        body: JSON.stringify({
          messages: updated.map(m => ({ role: m.role, content: m.content })),
          tripContext: `Trip: ${draftTrip.title}\nDestination: ${draftTrip.destination}\nDuration: ${draftTrip.duration}`,
          currentItinerary: draftTrip.aiItinerary,
          destination: draftTrip.destination,
        }),
      });
      const data = await res.json();
      const assistantMsg: ChatMsg = {
        role: "assistant",
        content: data.reply || "No response",
        changes: data.changes,
        hasModification: data.hasModification,
      };
      setChatMessages([...updated, assistantMsg]);
      if (data.hasModification && data.updatedItinerary) {
        setPrevItinerary(draftTrip.aiItinerary || null);
        setDraftTrip(prev => ({ ...prev, aiItinerary: data.updatedItinerary }));
        setItineraryVersion(v => v + 1);
        setExpandedDays(new Set([1]));
      }
    } catch {
      setChatMessages([...updated, { role: "assistant", content: "Something went wrong. Try again." }]);
    } finally {
      setChatLoading(false);
      setTimeout(() => chatEndRef.current?.scrollIntoView({ behavior: "smooth" }), 100);
    }
  }

  const totalActivities = draftTrip.aiItinerary?.reduce((s, d) => s + (d.activities?.length ?? 0), 0) || 0;
  const actualDays = draftTrip.aiItinerary?.length || 0;
  const displayDuration = actualDays > 0 ? `${actualDays} days` : draftTrip.duration;

  return (
    <motion.div
      className="fixed inset-0 z-[100] isolate flex overflow-hidden text-[#18211f]"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      {/* Backdrop */}
      <AmbientBackground />

      {/* ── LEFT: Chat Panel ──────────────────────────────────────── */}
      <motion.div
        className="relative z-10 flex w-full max-w-[430px] min-w-0 flex-col border-r border-white/60 bg-[#fffaf2]/74 shadow-[30px_0_90px_-62px_rgba(20,47,43,0.82)] backdrop-blur-2xl sm:min-w-[390px]"
        initial={{ x: -40, opacity: 0 }}
        animate={{ x: 0, opacity: 1 }}
        transition={{ delay: 0.1 }}
      >
        {/* Chat header */}
        <div className="border-b border-white/60 bg-white/36 px-4 py-4 shadow-[0_16px_36px_-34px_rgba(20,47,43,0.65)]">
          <div className="flex items-center gap-3">
            <button
              onClick={onClose}
              className="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full border border-white/60 bg-white/50 text-[#3a4a44] shadow-sm transition-all hover:bg-white hover:text-[#123d36] cursor-pointer"
              title="Back to home"
            >
              <ArrowLeft size={15} />
            </button>
            <button onClick={onClose} className="cursor-pointer">
              <Logo size="sm" className="min-w-0 [&>span]:text-xl" />
            </button>
          </div>
          {prevItinerary && (
            <button
              onClick={() => { setDraftTrip(prev => ({ ...prev, aiItinerary: prevItinerary })); setPrevItinerary(null); }}
              className="mt-3 inline-flex items-center gap-1 rounded-full border border-orange-200 bg-orange-50 px-2.5 py-1 text-[10px] text-orange-600 transition-colors hover:bg-orange-100 cursor-pointer"
            >
              <Undo2 size={10} /> Undo
            </button>
          )}
        </div>

        {/* Trip version tag */}
        <div className="border-b border-white/45 px-4 py-3">
          <div className="rounded-2xl border border-white/72 bg-white/58 p-3 shadow-[0_18px_42px_-36px_rgba(20,47,43,0.72)]">
            <div className="flex items-start gap-2.5">
              <span className="mt-1.5 h-2 w-2 rounded-full bg-[#123d36] shadow-[0_0_0_4px_rgba(18,61,54,0.1)]" />
              <div className="min-w-0 flex-1">
                <p className="truncate text-sm font-black text-[#17211f]">
                  {actualDays > 0 ? `${draftTrip.destination} — ${actualDays}-Day Trip` : draftTrip.title}
                </p>
                <p className="mt-1 text-[11px] font-semibold text-[#6a788f]">
                  Latest version · {chatMessages.filter(m => m.hasModification).length} modification(s)
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Quick action chips */}
        <div className="border-b border-white/45 px-4 py-3">
          <p className="mb-2 text-[10px] font-black uppercase tracking-[0.18em] text-[#6b768c]">Quick actions</p>
          <div className="grid grid-cols-2 gap-2">
            {["Make it vegetarian 🥗", "Budget-friendly 💰", "Add nightlife 🌙", "More relaxed 🧘"].map(chip => (
              <button
                key={chip}
                onClick={() => void handleChatSend(chip)}
                className="min-h-9 rounded-full border border-white/75 bg-white/68 px-3 text-left text-[11px] font-bold text-[#5e6a64] shadow-sm transition-all hover:-translate-y-0.5 hover:border-[#d5653e]/35 hover:bg-white hover:text-[#123d36] cursor-pointer"
              >
                {chip}
              </button>
            ))}
          </div>
        </div>

        {/* Chat messages */}
        <div className="flex-1 overflow-y-auto px-4 py-3 space-y-3">
          {chatMessages.length === 0 && (
            <div className="flex min-h-[300px] flex-col justify-center rounded-[1.35rem] border border-white/62 bg-white/30 px-6 py-8 text-center shadow-[inset_0_1px_0_rgba(255,255,255,0.55)]">
              <Logo size="md" showText={false} className="mx-auto mb-4" />
              <p className="text-base font-black text-[#17211f]">Refine this trip</p>
              <p className="mx-auto mt-2 max-w-[280px] text-sm leading-6 text-[#657488]">
                Ask for pacing, food, budget, activity swaps, or a better night plan.
              </p>
            </div>
          )}

          {chatMessages.map((msg, i) => (
            <motion.div key={i} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
              {msg.role === "user" ? (
                <div className="flex justify-end">
                  <div className="max-w-[85%] px-3.5 py-2 rounded-2xl rounded-br-sm bg-trippy-500 text-white text-xs leading-relaxed shadow-sm">
                    {msg.content}
                  </div>
                </div>
              ) : (
                <div className="space-y-2">
                  {msg.changes && msg.changes.length > 0 && (
                    <div className="space-y-1.5">
                      {msg.changes.map((c, ci) => (
                        <motion.div key={ci} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: ci * 0.1 }}
                          className={`flex items-start gap-2.5 px-3 py-2.5 rounded-xl border text-xs ${
                            c.type === "swap" ? "border-blue-200 bg-blue-50/80" :
                            c.type === "add" ? "border-green-200 bg-green-50/80" :
                            c.type === "remove" ? "border-red-200 bg-red-50/80" :
                            "border-amber-200 bg-amber-50/80"
                          }`}
                        >
                          <div className={`w-6 h-6 rounded-full flex items-center justify-center shrink-0 ${
                            c.type === "swap" ? "bg-blue-500" : c.type === "add" ? "bg-green-500" : c.type === "remove" ? "bg-red-500" : "bg-amber-500"
                          }`}>
                            {c.type === "swap" ? <ArrowRightLeft size={11} className="text-white" /> :
                             c.type === "add" ? <Plus size={11} className="text-white" /> :
                             c.type === "remove" ? <Trash2 size={11} className="text-white" /> :
                             <Lightbulb size={11} className="text-white" />}
                          </div>
                          <div className="flex-1 min-w-0">
                            {c.dayNumber && <span className="font-bold text-foreground">Day {c.dayNumber} · </span>}
                            <span className="text-foreground/80">{c.summary}</span>
                          </div>
                        </motion.div>
                      ))}
                    </div>
                  )}
                  {(!msg.changes || msg.changes.length === 0) && (
                    <div className="px-3.5 py-2.5 rounded-2xl rounded-bl-sm border border-white/70 bg-white/72 text-xs text-foreground leading-relaxed shadow-sm">
                      {msg.content.split("\n").map((line, li) => {
                        if (line.includes("**")) return <p key={li} className="font-semibold mt-1">{line.replace(/\*\*/g, "")}</p>;
                        if (line.startsWith("•") || line.startsWith("-")) return <p key={li} className="pl-2 text-muted">{line}</p>;
                        if (line.startsWith("*") && line.endsWith("*")) return <p key={li} className="italic text-[10px] text-trippy-600 mt-1">{line.replace(/\*/g, "")}</p>;
                        return line ? <p key={li}>{line}</p> : <br key={li} />;
                      })}
                    </div>
                  )}
                  {msg.hasModification && (
                    <div className="flex items-center gap-1.5 text-[10px] text-green-600 font-medium pl-1">
                      <Check size={10} /> Trip updated — see itinerary →
                    </div>
                  )}
                </div>
              )}
            </motion.div>
          ))}

          {chatLoading && (
            <div className="flex justify-start">
              <div className="border border-white/70 bg-white/72 px-4 py-3 rounded-2xl rounded-bl-sm flex items-center gap-2 shadow-sm">
                <Loader2 size={14} className="animate-spin text-trippy-500" />
                <span className="text-xs text-muted">Updating your trip with AI…</span>
              </div>
            </div>
          )}
          <div ref={chatEndRef} />
        </div>

        {/* Chat input */}
        <form
          onSubmit={(e) => { e.preventDefault(); void handleChatSend(); }}
          className="border-t border-white/70 bg-[linear-gradient(180deg,rgba(255,250,242,0.72),rgba(255,250,242,0.96))] px-4 pb-4 pt-3 shadow-[0_-24px_56px_-44px_rgba(20,47,43,0.9)] backdrop-blur-2xl"
        >
          <div className="mb-2 flex items-center justify-between px-1">
            <span className="text-[10px] font-black uppercase tracking-[0.18em] text-[#64736b]">Ask Trippy</span>
            <span className="text-[10px] font-semibold text-[#8b978f]">Trip edits, food, pace, budget</span>
          </div>
          <div className="flex items-center gap-2 rounded-[1.15rem] border border-[#d9cec0] bg-white px-3 py-3 shadow-[0_18px_46px_-30px_rgba(20,47,43,0.75),inset_0_1px_0_rgba(255,255,255,0.9)] focus-within:border-[#d5653e] focus-within:shadow-[0_0_0_4px_rgba(213,101,62,0.12),0_22px_52px_-34px_rgba(20,47,43,0.85)]">
            <input
              value={chatInput}
              onChange={(e) => setChatInput(e.target.value)}
              placeholder="Tell Trippy what to change..."
              className="min-h-7 flex-1 bg-transparent text-sm font-semibold text-[#17211f] outline-none placeholder:text-[#a2aca5]"
            />
            <button type="submit" disabled={chatLoading || !chatInput.trim()}
              className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#123d36] text-white shadow-[0_16px_30px_-20px_rgba(20,47,43,0.95)] transition-all hover:-translate-y-0.5 hover:bg-[#1d5148] disabled:cursor-not-allowed disabled:bg-[#b8c0bb] disabled:opacity-75 cursor-pointer"
            >
              <Send size={16} />
            </button>
          </div>
        </form>
      </motion.div>

      {/* ── RIGHT: Trip Details ────────────────────────────────────── */}
      <motion.div
        className="relative z-10 flex-1 overflow-y-auto"
        initial={{ opacity: 0, x: 20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.15 }}
      >
        <div className="max-w-4xl mx-auto px-8 py-6 space-y-5">
          {/* Hero image + info */}
          <div className="relative rounded-2xl overflow-hidden h-80 shadow-xl">
            <img
              src={draftTrip.image}
              alt={draftTrip.destination}
              className="w-full h-full object-cover"
              onError={(e) => { (e.target as HTMLImageElement).src = "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80"; }}
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/20 to-black/10" />
            <div className="absolute bottom-0 left-0 right-0 p-6">
              <h1 className="text-white font-black text-2xl drop-shadow-lg leading-tight">
                {actualDays > 0 ? `${draftTrip.destination} — ${actualDays}-Day Trip` : draftTrip.title}
              </h1>
              <div className="flex items-center gap-4 mt-2.5 flex-wrap">
                <span className="flex items-center gap-1.5 text-white/90 text-sm font-medium">
                  <MapPin size={13} />
                  <a
                    href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(draftTrip.destination)}`}
                    target="_blank"
                    rel="noreferrer"
                    className="hover:text-white hover:underline"
                  >
                    {draftTrip.destination}
                  </a>
                </span>
                <span className="flex items-center gap-1.5 text-white/90 text-sm font-medium">
                  <Calendar size={13} /> {displayDuration}
                </span>
                <span className="flex items-center gap-1.5 text-white/90 text-sm font-medium">
                  <Users size={13} /> {draftTrip.groupSize} people
                </span>
              </div>
            </div>
          </div>

          {/* Trip stats bar */}
          <div className="grid grid-cols-2 lg:grid-cols-3 gap-3">
            {[
              { icon: <Sparkles size={16} className="text-purple-500" />, label: "Activities", value: `${totalActivities} planned`, bg: "bg-purple-50 border-purple-100" },
              { icon: <DollarSign size={16} className="text-amber-500" />, label: "Budget", value: draftTrip.budget, bg: "bg-amber-50 border-amber-100" },
              { icon: <Calendar size={16} className="text-trippy-500" />, label: "Duration", value: displayDuration, bg: "bg-trippy-500/5 border-trippy-200" },
            ].map((s, i) => (
              <div key={i} className={`flex items-center gap-3 rounded-xl border px-4 py-3 ${s.bg}`}>
                <div className="shrink-0">{s.icon}</div>
                <div className="min-w-0">
                  <p className="text-[10px] font-bold uppercase tracking-wider text-muted">{s.label}</p>
                  <p className="text-sm font-bold text-foreground truncate">{s.value}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Itinerary */}
          {itineraryLoading ? (
            <div className="flex flex-col items-center justify-center py-16 gap-4">
              <div className="w-16 h-16 rounded-2xl bg-trippy-500/10 flex items-center justify-center">
                <Loader2 size={28} className="animate-spin text-trippy-500" />
              </div>
              <div className="text-center">
                <p className="text-sm font-semibold text-foreground">Building your itinerary…</p>
                <p className="text-xs text-muted mt-1">This takes a few seconds</p>
              </div>
            </div>
          ) : draftTrip.aiItinerary && draftTrip.aiItinerary.length > 0 ? (
            <div className="relative">
              {/* Loading overlay while chat is regenerating */}
              <AnimatePresence>
                {chatLoading && (
                  <motion.div
                    key="itinerary-overlay"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.2 }}
                    className="absolute inset-0 z-10 flex flex-col items-center justify-center rounded-2xl bg-white/85 backdrop-blur-[4px]"
                  >
                    <Loader2 size={32} className="animate-spin text-trippy-500 mb-3" />
                    <p className="text-sm font-semibold text-foreground">Updating with AI…</p>
                    <p className="text-xs text-muted mt-1">Regenerating your itinerary</p>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* Itinerary header + day navigator */}
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-base font-black text-foreground flex items-center gap-2">
                  <Sparkles size={16} className="text-trippy-500" />
                  Your Itinerary
                </h2>
                <div className="flex items-center gap-2">
                  <button
                    onClick={() => setExpandedDays(new Set(draftTrip.aiItinerary?.map(d => d.dayNumber) ?? []))}
                    className="text-[11px] font-semibold text-trippy-600 hover:text-trippy-700 cursor-pointer transition-colors px-2.5 py-1 rounded-lg hover:bg-trippy-500/10"
                  >
                    Expand all
                  </button>
                  <button
                    onClick={() => setExpandedDays(new Set())}
                    className="text-[11px] font-semibold text-muted hover:text-foreground cursor-pointer transition-colors px-2.5 py-1 rounded-lg hover:bg-surface"
                  >
                    Collapse all
                  </button>
                </div>
              </div>

              {/* Day navigator pills */}
              <div className="flex gap-2 overflow-x-auto pb-3 mb-4 no-scrollbar">
                {draftTrip.aiItinerary.map(day => {
                  const isExp = expandedDays.has(day.dayNumber);
                  const hasWeather = day.weather?.condition && !day.weather.condition.includes("unavailable");
                  return (
                    <button
                      key={day.dayNumber}
                      onClick={() => {
                        if (!isExp) toggleDay(day.dayNumber);
                        setTimeout(() => {
                          document.getElementById(`day-${itineraryVersion}-${day.dayNumber}`)?.scrollIntoView({ behavior: "smooth", block: "start" });
                        }, 50);
                      }}
                      className={`flex items-center gap-2 shrink-0 px-3.5 py-2 rounded-full border text-xs font-bold transition-all cursor-pointer ${
                        isExp
                          ? "bg-trippy-500 border-trippy-500 text-white shadow-md shadow-trippy-500/30"
                          : "bg-white border-border/60 text-foreground hover:border-trippy-400 hover:text-trippy-600"
                      }`}
                    >
                      <span>Day {day.dayNumber}</span>
                      {hasWeather && (
                        <span className={`text-[9px] font-medium ${isExp ? "text-white/80" : "text-sky-600"}`}>
                          {formatTemperature(day.weather!.temperatureCelsius)}
                        </span>
                      )}
                    </button>
                  );
                })}
              </div>

              {draftTrip.aiItinerary.map((day, dayIdx) => {
                const isExpanded = expandedDays.has(day.dayNumber);
                const isEditingThisDay = editingDayNum === day.dayNumber;
                const dateStr = day.date
                  ? new Date(day.date).toLocaleDateString(undefined, { weekday: "long", day: "numeric", month: "short" })
                  : "";
                const weatherCondition = day.weather?.condition;
                const hasWeather = weatherCondition && !weatherCondition.includes("unavailable");
                const weatherTemp = formatTemperature(day.weather?.temperatureCelsius);
                const weatherIcon = getWeatherIcon(weatherCondition);

                return (
                  <motion.div
                    id={`day-${itineraryVersion}-${day.dayNumber}`}
                    key={`${itineraryVersion}-day-${day.dayNumber}`}
                    className="mb-4 scroll-mt-4"
                    initial={{ opacity: 0, y: 16 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: dayIdx * 0.06, duration: 0.3, ease: "easeOut" }}
                  >
                    <div className="rounded-2xl border border-border/60 overflow-hidden bg-white shadow-sm hover:shadow-md transition-shadow">
                      {/* Day header */}
                      <div className={`flex items-center gap-3 px-5 py-4 transition-colors ${isExpanded ? "bg-trippy-500/[0.03] border-b border-border/40" : "hover:bg-trippy-500/[0.02]"}`}>
                        <button
                          onClick={() => toggleDay(day.dayNumber)}
                          className="flex-1 flex items-center gap-4 text-left cursor-pointer min-w-0"
                        >
                          {/* Day number badge */}
                          <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-trippy-500 to-trippy-600 text-white flex flex-col items-center justify-center font-black shadow-md shadow-trippy-500/25 shrink-0">
                            <span className="text-[9px] font-bold opacity-80 leading-none">DAY</span>
                            <span className="text-base leading-none">{day.dayNumber}</span>
                          </div>
                          <div className="flex-1 min-w-0">
                            {isEditingThisDay ? (
                              <input
                                value={editDayTitle}
                                onChange={(e) => setEditDayTitle(e.target.value)}
                                onKeyDown={(e) => {
                                  if (e.key === "Enter") saveEditDay();
                                  if (e.key === "Escape") setEditingDayNum(null);
                                }}
                                onClick={(e) => e.stopPropagation()}
                                autoFocus
                                className="text-sm font-bold text-foreground bg-transparent border-b-2 border-trippy-400 outline-none w-full pb-0.5"
                              />
                            ) : (
                              <p className="text-sm font-bold text-foreground leading-tight">{day.title}</p>
                            )}
                            <div className="flex items-center gap-2 mt-0.5 flex-wrap">
                              {dateStr && <span className="text-[11px] text-muted">{dateStr}</span>}
                              <span className="text-[11px] text-muted bg-surface px-2 py-0.5 rounded-full">
                                {(day.activities?.length ?? 0)} activities
                              </span>
                            </div>
                          </div>
                          {/* Weather badge in header */}
                          {hasWeather && (
                            <div className="shrink-0 flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-sky-50 border border-sky-200 text-sky-700">
                              <span className="text-sm leading-none">{weatherIcon}</span>
                              <span className="text-[11px] font-semibold whitespace-nowrap">
                                {weatherCondition!.split("(")[0].trim()}
                                {weatherTemp && <span className="ml-1 font-bold">{weatherTemp}</span>}
                              </span>
                            </div>
                          )}
                          {isExpanded ? <ChevronUp size={16} className="text-muted shrink-0" /> : <ChevronDown size={16} className="text-muted shrink-0" />}
                        </button>

                        {/* Edit / Save day title button */}
                        {isEditingThisDay ? (
                          <div className="flex items-center gap-1.5 shrink-0">
                            <button
                              onClick={saveEditDay}
                              className="text-[10px] font-semibold text-white bg-trippy-500 px-2.5 py-1 rounded-full hover:bg-trippy-600 cursor-pointer transition-colors"
                            >
                              Save
                            </button>
                            <button
                              onClick={() => setEditingDayNum(null)}
                              className="text-[10px] text-muted border border-border px-2.5 py-1 rounded-full hover:text-foreground cursor-pointer transition-colors"
                            >
                              Cancel
                            </button>
                          </div>
                        ) : (
                          <button
                            onClick={(e) => { e.stopPropagation(); startEditDay(day.dayNumber, day.title); }}
                            title="Edit day title"
                            className="shrink-0 w-7 h-7 rounded-lg flex items-center justify-center text-muted hover:text-trippy-600 hover:bg-trippy-500/10 transition-colors cursor-pointer"
                          >
                            <Pencil size={12} />
                          </button>
                        )}
                      </div>

                      <AnimatePresence>
                        {isExpanded && (
                          <motion.div
                            initial={{ height: 0 }}
                            animate={{ height: "auto" }}
                            exit={{ height: 0 }}
                            className="overflow-hidden"
                          >
                            <div className="border-t border-border/40">
                              <DayContextBlocks day={day} />
                              <div className="px-5 py-4 space-y-0">
                                {(day.activities ?? []).map((act, idx) => {
                                  const cat = act.category || "";
                                  const durationMinutes = act.durationMinutes ?? act.duration;
                                  const isEditingThis =
                                    editingActivity?.dayNumber === day.dayNumber &&
                                    editingActivity?.idx === idx;
                                  const isLast = idx === (day.activities?.length ?? 0) - 1;

                                  return (
                                    <div key={idx} className="group relative flex gap-4">
                                      {/* Timeline spine */}
                                      <div className="flex flex-col items-center shrink-0 w-16">
                                        {act.time ? (
                                          <span className="text-[10px] font-black text-trippy-600 bg-trippy-500/10 border border-trippy-200 px-2 py-1 rounded-lg text-center leading-tight whitespace-nowrap z-10">
                                            {act.time}
                                          </span>
                                        ) : (
                                          <div className="w-3 h-3 rounded-full bg-trippy-400 border-2 border-white shadow-sm z-10 mt-1" />
                                        )}
                                        {!isLast && (
                                          <div className="w-0.5 flex-1 bg-gradient-to-b from-trippy-200 to-trippy-100 my-1 min-h-[24px]" />
                                        )}
                                      </div>

                                      {/* Activity card */}
                                      <div className={`flex-1 min-w-0 pb-4 ${isLast ? "" : ""}`}>
                                        {isEditingThis ? (
                                          /* ── Inline edit form ── */
                                          <div className="rounded-xl px-4 py-3 bg-trippy-500/[0.03] space-y-2.5 border border-trippy-300 mb-2">
                                            <p className="text-[10px] font-bold text-trippy-700 uppercase tracking-wider">Edit Activity</p>
                                            <div className="grid grid-cols-2 gap-2">
                                              <input
                                                value={editActivityForm.title}
                                                onChange={(e) => setEditActivityForm(f => ({ ...f, title: e.target.value }))}
                                                placeholder="Activity title *"
                                                autoFocus
                                                className="col-span-2 text-xs rounded-lg border border-trippy-300 px-2.5 py-1.5 outline-none bg-white focus:border-trippy-500"
                                              />
                                              <input
                                                type="time"
                                                value={editActivityForm.time}
                                                onChange={(e) => setEditActivityForm(f => ({ ...f, time: e.target.value }))}
                                                className="text-xs rounded-lg border border-border px-2.5 py-1.5 outline-none bg-white focus:border-trippy-500/50"
                                              />
                                              <input
                                                value={editActivityForm.estimatedCost}
                                                onChange={(e) => setEditActivityForm(f => ({ ...f, estimatedCost: e.target.value }))}
                                                placeholder="Cost (e.g. $20)"
                                                className="text-xs rounded-lg border border-border px-2.5 py-1.5 outline-none bg-white focus:border-trippy-500/50"
                                              />
                                              <input
                                                value={editActivityForm.location}
                                                onChange={(e) => setEditActivityForm(f => ({ ...f, location: e.target.value }))}
                                                placeholder="Location / Address"
                                                className="col-span-2 text-xs rounded-lg border border-border px-2.5 py-1.5 outline-none bg-white focus:border-trippy-500/50"
                                              />
                                              <textarea
                                                value={editActivityForm.description}
                                                onChange={(e) => setEditActivityForm(f => ({ ...f, description: e.target.value }))}
                                                placeholder="Description (optional)"
                                                rows={2}
                                                className="col-span-2 text-xs rounded-lg border border-border px-2.5 py-1.5 outline-none bg-white resize-none focus:border-trippy-500/50"
                                              />
                                            </div>
                                            <div className="flex gap-2">
                                              <button
                                                onClick={saveEditActivity}
                                                disabled={!editActivityForm.title.trim()}
                                                className="text-[10px] font-semibold text-white bg-trippy-500 px-3.5 py-1.5 rounded-full cursor-pointer hover:bg-trippy-600 disabled:opacity-40 transition-colors"
                                              >
                                                Save changes
                                              </button>
                                              <button
                                                onClick={() => setEditingActivity(null)}
                                                className="text-[10px] text-muted border border-border px-3.5 py-1.5 rounded-full cursor-pointer hover:text-foreground transition-colors"
                                              >
                                                Cancel
                                              </button>
                                            </div>
                                          </div>
                                        ) : (
                                          /* ── Activity card ── */
                                          <div className="rounded-xl border border-border/50 bg-white hover:border-trippy-300/60 hover:shadow-sm transition-all px-4 py-3 mb-2 group/card relative">
                                            {/* Edit/Delete on hover */}
                                            <div className="absolute top-2.5 right-2.5 flex items-center gap-1 opacity-0 group-hover/card:opacity-100 transition-opacity z-10">
                                              <button
                                                onClick={() => startEditActivity(day.dayNumber, idx, act)}
                                                title="Edit"
                                                className="w-6 h-6 rounded-lg flex items-center justify-center text-muted hover:text-trippy-600 hover:bg-trippy-500/10 transition-colors cursor-pointer"
                                              >
                                                <Pencil size={11} />
                                              </button>
                                              <button
                                                onClick={() => deleteActivity(day.dayNumber, idx)}
                                                title="Delete"
                                                className="w-6 h-6 rounded-lg flex items-center justify-center text-muted hover:text-red-500 hover:bg-red-50 transition-colors cursor-pointer"
                                              >
                                                <Trash2 size={11} />
                                              </button>
                                            </div>

                                            <div className="flex items-start gap-3 pr-14">
                                              {/* Category emoji */}
                                              <span className="text-xl leading-none mt-0.5 shrink-0">{CAT_ICONS[cat] || "📌"}</span>
                                              <div className="flex-1 min-w-0">
                                                <div className="flex items-center gap-2 flex-wrap">
                                                  <p className="text-sm font-bold text-foreground leading-tight">{act.title}</p>
                                                  {cat && (
                                                    <span className={`text-[9px] font-bold px-2 py-0.5 rounded-full border uppercase tracking-wide ${CAT_COLORS[cat] || "bg-gray-100 text-gray-600 border-gray-200"}`}>
                                                      {cat}
                                                    </span>
                                                  )}
                                                  {act.bookingRequired && (
                                                    <span className="text-[9px] font-bold text-blue-700 bg-blue-50 border border-blue-200 px-2 py-0.5 rounded-full">
                                                      📅 Book ahead
                                                    </span>
                                                  )}
                                                </div>
                                                {act.description && (
                                                  <p className="text-[12px] text-muted mt-1 leading-relaxed">{act.description}</p>
                                                )}
                                                <div className="flex flex-wrap items-center gap-3 mt-2">
                                                  {durationMinutes && (
                                                    <span className="text-[11px] text-muted flex items-center gap-1 font-medium">
                                                      <Clock size={10} className="text-trippy-400" /> {formatDurationMinutes(durationMinutes)}
                                                    </span>
                                                  )}
                                                  {act.location && (
                                                    <span className="text-[11px] text-muted flex items-center gap-1 font-medium">
                                                      <MapPin size={10} className="text-trippy-400" />
                                                      {act.location}
                                                    </span>
                                                  )}
                                                  {act.location && (
                                                    <a
                                                      href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${act.location}, ${draftTrip.destination}`)}`}
                                                      target="_blank"
                                                      rel="noreferrer"
                                                      className="inline-flex items-center gap-1 rounded-full border border-blue-200 bg-blue-50 px-2.5 py-0.5 text-[11px] font-semibold text-blue-600 hover:bg-blue-100 transition-colors"
                                                    >
                                                      <MapPin size={9} /> Open in Maps
                                                    </a>
                                                  )}
                                                  {act.estimatedCost && (
                                                    <span className="text-[11px] font-bold text-amber-700 bg-amber-50 border border-amber-200 px-2.5 py-0.5 rounded-lg flex items-center gap-1">
                                                      <DollarSign size={9} /> {act.estimatedCost}
                                                    </span>
                                                  )}
                                                </div>
                                                {act.tips && (
                                                  <p className="text-[11px] text-trippy-600/70 mt-2 leading-relaxed italic border-l-2 border-trippy-200 pl-2">
                                                    💡 {act.tips}
                                                  </p>
                                                )}
                                              </div>
                                            </div>
                                          </div>
                                        )}
                                      </div>
                                    </div>
                                  );
                                })}

                                {/* Add activity */}
                                <button
                                  onClick={() => addActivity(day.dayNumber)}
                                  className="flex items-center gap-2 text-[11px] font-semibold text-trippy-600 hover:text-trippy-700 cursor-pointer transition-colors mt-1 px-2 py-1.5 rounded-lg hover:bg-trippy-500/10"
                                >
                                  <Plus size={12} className="text-trippy-500" /> Add activity
                                </button>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          ) : itineraryError ? (
            <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800">
              {itineraryError}
            </div>
          ) : null}

          {/* Save bar */}
          <div className="sticky bottom-0 bg-gradient-to-t from-[#f7f6f3] via-[#f7f6f3]/95 to-transparent pt-6 pb-6">
            <Button className="w-full text-sm py-3.5 shadow-lg shadow-trippy-500/20" onClick={onSave} disabled={saved}>
              {saved ? <><Check size={16} /> Trip Saved to Dashboard</> : <><Sparkles size={16} /> Save This Trip</>}
            </Button>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}

function DayContextBlocks({ day }: { day: AiItineraryDay }) {
  const transport = day.transportRecommendations?.filter((item) =>
    Boolean((item.from || item.to) && (item.estimatedDuration || item.notes))
  ) ?? [];

  if (transport.length === 0) return null;

  return (
    <div className="bg-[#f9f9f7] px-5 py-4">
      <div className="rounded-xl border border-emerald-200 bg-emerald-50/60 px-4 py-3">
        <div className="flex items-center gap-2">
          <Bus size={14} className="text-emerald-600" />
          <span className="text-[11px] font-black uppercase tracking-wider text-emerald-700">Transit</span>
        </div>
        <div className="mt-1.5 space-y-2">
          {transport.slice(0, 3).map((item, idx) => (
            <div key={`${item.from}-${item.to}-${idx}`} className="text-[11px] leading-relaxed">
              <p className="font-bold text-foreground/80">
                {item.from || "Start"} → {item.to || "Next stop"}
              </p>
              <p className="text-muted">
                {[item.mode || "Route", item.estimatedDuration].filter(Boolean).join(" · ")}
              </p>
              {item.notes && <p className="text-muted">{item.notes}</p>}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function getWeatherIcon(condition: string | undefined): string {
  if (!condition) return "🌤️";
  const c = condition.toLowerCase();
  if (c.includes("clear")) return "☀️";
  if (c.includes("mainly clear")) return "🌤️";
  if (c.includes("partly cloudy")) return "⛅";
  if (c.includes("overcast") || c.includes("cloud")) return "☁️";
  if (c.includes("fog")) return "🌫️";
  if (c.includes("drizzle")) return "🌦️";
  if (c.includes("thunderstorm")) return "⛈️";
  if (c.includes("snow")) return "🌨️";
  if (c.includes("rain")) return "🌧️";
  if (c.includes("warm") || c.includes("summer")) return "☀️";
  if (c.includes("cold") || c.includes("winter") || c.includes("frost")) return "🌨️";
  if (c.includes("mild") || c.includes("spring")) return "🌸";
  if (c.includes("cool") || c.includes("autumn")) return "🍂";
  return "🌤️";
}

function formatTemperature(value?: number | null): string {
  if (typeof value !== "number" || !Number.isFinite(value)) return "";
  return `${Math.round(value)}°C`;
}

function formatDurationMinutes(value: number): string {
  if (!Number.isFinite(value) || value <= 0) return "";
  if (value < 60) return `${value} min`;
  const hours = Math.floor(value / 60);
  const minutes = value % 60;
  return minutes ? `${hours}h ${minutes}m` : `${hours}h`;
}

function aiRequestHeaders(): Record<string, string> {
  const token = getAccessToken();
  return token
    ? { "Content-Type": "application/json", Authorization: `Bearer ${token}` }
    : { "Content-Type": "application/json" };
}
