"use client";

import React, { useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  X, MapPin, Calendar, Users, Sparkles, Loader2, Check, Star,
  DollarSign, MessageSquare, Send, ArrowRightLeft, Plus, Trash2,
  Lightbulb, Undo2, ChevronDown, ChevronUp, ArrowLeft, Pencil,
  RefreshCw,
} from "lucide-react";
import Button from "@/components/ui/Button";

/* ── Types ─────────────────────────────────────────────────────────── */
interface AiItineraryDay {
  dayNumber: number;
  date?: string;
  title: string;
  activities: { time?: string; title: string; description?: string; location?: string; estimatedCost?: string }[];
}

interface GeneratedTrip {
  title: string;
  destination: string;
  duration: string;
  budget: string;
  groupSize: string;
  rating: number;
  highlights: string[];
  reason: string;
  bestTimeToVisit: string;
  image: string;
  aiItinerary?: AiItineraryDay[];
}

interface ChatChange {
  type: string;
  dayNumber?: number;
  removed?: string;
  added?: string;
  summary: string;
}

interface ChatMsg {
  role: "user" | "assistant";
  content: string;
  changes?: ChatChange[];
  hasModification?: boolean;
}

interface TripFullScreenViewProps {
  trip: GeneratedTrip;
  userPrompt?: string;
  userDates?: { start: string; end: string };
  onBack: () => void;
  onClose: () => void;
  onSave: () => void;
  saved: boolean;
  onRegenerate?: () => void;
  onEditSearch?: () => void;
}

const CAT_COLORS: Record<string, string> = {
  FOOD: "bg-orange-100 text-orange-700 border-orange-200",
  SIGHTSEEING: "bg-blue-100 text-blue-700 border-blue-200",
  TRANSPORT: "bg-slate-100 text-slate-600 border-slate-200",
  SHOPPING: "bg-pink-100 text-pink-700 border-pink-200",
  CULTURE: "bg-purple-100 text-purple-700 border-purple-200",
  NIGHTLIFE: "bg-indigo-100 text-indigo-700 border-indigo-200",
  NATURE: "bg-green-100 text-green-700 border-green-200",
  WELLNESS: "bg-teal-100 text-teal-700 border-teal-200",
};

const CAT_ICONS: Record<string, string> = {
  FOOD: "🍽️", SIGHTSEEING: "👁️", TRANSPORT: "🚌", SHOPPING: "🛍️",
  CULTURE: "🏛️", NIGHTLIFE: "🌙", NATURE: "🌿", WELLNESS: "🧘",
};

/* ── Main Component ────────────────────────────────────────────────── */
export default function TripFullScreenView({
  trip, userPrompt, userDates, onBack, onClose, onSave, saved, onRegenerate, onEditSearch,
}: TripFullScreenViewProps) {
  const [draftTrip, setDraftTrip] = useState<GeneratedTrip>(trip);
  const [itineraryLoading, setItineraryLoading] = useState(false);
  const [chatMessages, setChatMessages] = useState<ChatMsg[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [chatLoading, setChatLoading] = useState(false);
  const [prevItinerary, setPrevItinerary] = useState<AiItineraryDay[] | null>(null);
  const [expandedDays, setExpandedDays] = useState<Set<number>>(new Set([1]));
  const chatEndRef = useRef<HTMLDivElement>(null);
  const autoGenerated = useRef(false);

  /* ── Edit State ─────────────────────────────────────────────────── */
  const [editingDayNum, setEditingDayNum] = useState<number | null>(null);
  const [editDayTitle, setEditDayTitle] = useState("");
  const [editingActivity, setEditingActivity] = useState<{ dayNumber: number; idx: number } | null>(null);
  const [editActivityForm, setEditActivityForm] = useState({
    title: "", description: "", time: "", location: "", estimatedCost: "",
  });

  useEffect(() => { setDraftTrip(trip); }, [trip]);

  // Fetch city image
  useEffect(() => {
    if (!trip.destination) return;
    let cancelled = false;
    fetch(`/api/images/city?q=${encodeURIComponent(trip.destination)}`)
      .then(r => r.json())
      .then(d => { if (!cancelled && d?.image) setDraftTrip(prev => ({ ...prev, image: d.image })); })
      .catch(() => {});
    return () => { cancelled = true; };
  }, [trip.destination]);

  // Auto-generate itinerary
  useEffect(() => {
    if (!autoGenerated.current && !draftTrip.aiItinerary?.length) {
      autoGenerated.current = true;
      void generateItinerary();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function generateItinerary() {
    setItineraryLoading(true);
    try {
      const durationMatch = draftTrip.duration.match(/(\d+)/);
      const days = durationMatch ? parseInt(durationMatch[1]) : 3;
      const today = new Date();
      const startDate = today.toISOString().slice(0, 10);
      const endDateObj = new Date(today);
      endDateObj.setDate(endDateObj.getDate() + days - 1);
      const endDate = endDateObj.toISOString().slice(0, 10);

      const res = await fetch("/api/ai/itineraries", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          constraints: {
            destination: draftTrip.destination,
            startDate: userDates?.start || startDate,
            endDate: userDates?.end || endDate,
            budgetLevel: "MODERATE",
            adults: parseInt(draftTrip.groupSize) || 2,
            children: 0,
          },
          userPrompt: userPrompt
            ? `${userPrompt}. Highlights: ${draftTrip.highlights.join(", ")}`
            : `Highlights: ${draftTrip.highlights.join(", ")}`,
        }),
      });
      if (!res.ok) throw new Error("Failed");
      const data = await res.json();
      if (data.dailyPlan?.length) {
        setDraftTrip(prev => ({ ...prev, aiItinerary: data.dailyPlan }));
        setExpandedDays(new Set([1]));
      }
    } catch { /* silent */ }
    finally { setItineraryLoading(false); }
  }

  function toggleDay(day: number) {
    setExpandedDays(prev => {
      const next = new Set(prev);
      next.has(day) ? next.delete(day) : next.add(day);
      return next;
    });
  }

  /* ── Edit Functions ─────────────────────────────────────────────── */
  function startEditDay(dayNum: number, currentTitle: string) {
    setEditingDayNum(dayNum);
    setEditDayTitle(currentTitle);
    setEditingActivity(null);
    if (!expandedDays.has(dayNum)) toggleDay(dayNum);
  }

  function saveEditDay() {
    if (!editingDayNum) return;
    if (editDayTitle.trim()) {
      setDraftTrip(prev => ({
        ...prev,
        aiItinerary: prev.aiItinerary?.map(d =>
          d.dayNumber === editingDayNum ? { ...d, title: editDayTitle } : d
        ),
      }));
    }
    setEditingDayNum(null);
  }

  function deleteActivity(dayNumber: number, idx: number) {
    setDraftTrip(prev => ({
      ...prev,
      aiItinerary: prev.aiItinerary?.map(d =>
        d.dayNumber === dayNumber
          ? { ...d, activities: d.activities.filter((_, i) => i !== idx) }
          : d
      ),
    }));
  }

  function startEditActivity(dayNumber: number, idx: number, act: AiItineraryDay["activities"][0]) {
    setEditingActivity({ dayNumber, idx });
    setEditActivityForm({
      title: act.title || "",
      description: act.description || "",
      time: act.time || "",
      location: act.location || "",
      estimatedCost: act.estimatedCost || "",
    });
    setEditingDayNum(null);
  }

  function saveEditActivity() {
    if (!editingActivity) return;
    const { dayNumber, idx } = editingActivity;
    setDraftTrip(prev => ({
      ...prev,
      aiItinerary: prev.aiItinerary?.map(d =>
        d.dayNumber === dayNumber
          ? {
              ...d,
              activities: d.activities.map((a, i) =>
                i === idx ? { ...a, ...editActivityForm } : a
              ),
            }
          : d
      ),
    }));
    setEditingActivity(null);
  }

  function addActivity(dayNumber: number) {
    const day = draftTrip.aiItinerary?.find(d => d.dayNumber === dayNumber);
    const newIdx = day ? day.activities.length : 0;
    setDraftTrip(prev => ({
      ...prev,
      aiItinerary: prev.aiItinerary?.map(d =>
        d.dayNumber === dayNumber
          ? { ...d, activities: [...d.activities, { time: "", title: "New Activity", description: "", location: "", estimatedCost: "" }] }
          : d
      ),
    }));
    setEditingActivity({ dayNumber, idx: newIdx });
    setEditActivityForm({ title: "", description: "", time: "", location: "", estimatedCost: "" });
    setEditingDayNum(null);
  }

  async function handleChatSend(inputOverride?: string) {
    const text = inputOverride || chatInput.trim();
    if (!text || chatLoading) return;
    const newMsg: ChatMsg = { role: "user", content: text };
    const updated = [...chatMessages, newMsg];
    setChatMessages(updated);
    setChatInput("");
    setChatLoading(true);
    try {
      const res = await fetch("/api/ai/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: updated.map(m => ({ role: m.role, content: m.content })),
          tripContext: `Trip: ${draftTrip.title}\nDestination: ${draftTrip.destination}\nDuration: ${draftTrip.duration}`,
          currentItinerary: draftTrip.aiItinerary,
          destination: draftTrip.destination,
        }),
      });
      const data = await res.json();
      const assistantMsg: ChatMsg = {
        role: "assistant",
        content: data.reply || "No response",
        changes: data.changes,
        hasModification: data.hasModification,
      };
      setChatMessages([...updated, assistantMsg]);
      if (data.hasModification && data.updatedItinerary) {
        setPrevItinerary(draftTrip.aiItinerary || null);
        setDraftTrip(prev => ({ ...prev, aiItinerary: data.updatedItinerary }));
      }
    } catch {
      setChatMessages([...updated, { role: "assistant", content: "Something went wrong. Try again." }]);
    } finally {
      setChatLoading(false);
      setTimeout(() => chatEndRef.current?.scrollIntoView({ behavior: "smooth" }), 100);
    }
  }

  const totalActivities = draftTrip.aiItinerary?.reduce((s, d) => s + d.activities.length, 0) || 0;
  const actualDays = draftTrip.aiItinerary?.length || 0;
  const displayDuration = actualDays > 0 ? `${actualDays} days` : draftTrip.duration;

  return (
    <motion.div
      className="fixed inset-0 z-[100] flex"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      {/* Backdrop */}
      <div className="absolute inset-0 bg-[#f7f6f3]" />

      {/* ── LEFT: Chat Panel ──────────────────────────────────────── */}
      <motion.div
        className="relative z-10 w-[380px] min-w-[340px] max-w-[420px] flex flex-col border-r border-border/60 bg-white"
        initial={{ x: -40, opacity: 0 }}
        animate={{ x: 0, opacity: 1 }}
        transition={{ delay: 0.1 }}
      >
        {/* Chat header */}
        <div className="flex items-center gap-3 px-4 py-3 border-b border-border/60 bg-gradient-to-r from-trippy-500/5 to-transparent">
          <button
            onClick={onBack}
            title="Back to results"
            className="w-8 h-8 rounded-lg flex items-center justify-center hover:bg-surface transition-colors cursor-pointer"
          >
            <ArrowLeft size={16} className="text-muted" />
          </button>
          <div className="w-8 h-8 rounded-xl bg-trippy-500 flex items-center justify-center shadow-sm">
            <Sparkles size={14} className="text-white" />
          </div>
          <div className="flex-1 min-w-0">
            <h3 className="font-semibold text-sm truncate">Trippy AI</h3>
            <p className="text-[10px] text-muted">Modify your trip with chat</p>
          </div>
          {prevItinerary && (
            <button
              onClick={() => { setDraftTrip(prev => ({ ...prev, aiItinerary: prevItinerary })); setPrevItinerary(null); }}
              className="flex items-center gap-1 text-[10px] text-orange-600 bg-orange-50 border border-orange-200 px-2.5 py-1 rounded-full hover:bg-orange-100 cursor-pointer transition-colors"
            >
              <Undo2 size={10} /> Undo
            </button>
          )}
        </div>

        {/* ── Action bar: Regenerate / Change Dates / Close ─────── */}
        <div className="flex items-center gap-2 px-4 py-2.5 border-b border-border/40 flex-wrap bg-gradient-to-r from-trippy-500/[0.02] to-transparent">
          {onRegenerate && (
            <button
              onClick={onRegenerate}
              className="flex items-center gap-1.5 text-[10px] font-semibold text-trippy-700 bg-trippy-500/10 border border-trippy-500/20 px-3 py-1.5 rounded-full hover:bg-trippy-500/20 transition-colors cursor-pointer"
            >
              <RefreshCw size={10} /> Regenerate
            </button>
          )}
          {onEditSearch && (
            <button
              onClick={onEditSearch}
              className="flex items-center gap-1.5 text-[10px] font-semibold text-blue-700 bg-blue-50 border border-blue-200 px-3 py-1.5 rounded-full hover:bg-blue-100 transition-colors cursor-pointer"
            >
              <Calendar size={10} /> Change Dates
            </button>
          )}
          <button
            onClick={onClose}
            className="ml-auto flex items-center gap-1 text-[10px] text-muted hover:text-foreground cursor-pointer transition-colors"
          >
            <X size={11} /> Close
          </button>
        </div>

        {/* Trip version tag */}
        <div className="px-4 py-2 border-b border-border/40">
          <div className="inline-flex items-center gap-2 bg-trippy-500/8 border border-trippy-500/20 rounded-lg px-3 py-1.5">
            <div className="w-1.5 h-1.5 rounded-full bg-trippy-500 animate-pulse" />
            <span className="text-[10px] font-semibold text-trippy-700">
              {actualDays > 0 ? `${draftTrip.destination} — ${actualDays}-Day Trip` : draftTrip.title}
            </span>
          </div>
          <p className="text-[9px] text-muted mt-1">Latest version • {chatMessages.filter(m => m.hasModification).length} modification(s)</p>
        </div>

        {/* Quick action chips */}
        <div className="px-4 py-2 border-b border-border/40">
          <p className="text-[9px] text-muted mb-1.5 uppercase tracking-wider font-semibold">Quick actions</p>
          <div className="flex flex-wrap gap-1.5">
            {["Make it vegetarian 🥗", "Budget-friendly 💰", "Add nightlife 🌙", "More relaxed 🧘", "Adventure 🏔️"].map(chip => (
              <button
                key={chip}
                onClick={() => void handleChatSend(chip)}
                className="text-[10px] px-2.5 py-1 rounded-full border border-border/60 text-foreground/70 bg-white hover:bg-trippy-500/8 hover:border-trippy-500/30 hover:text-trippy-700 transition-all cursor-pointer"
              >
                {chip}
              </button>
            ))}
          </div>
        </div>

        {/* Chat messages */}
        <div className="flex-1 overflow-y-auto px-4 py-3 space-y-3">
          {chatMessages.length === 0 && (
            <div className="text-center py-8">
              <div className="w-12 h-12 rounded-2xl bg-trippy-500/10 flex items-center justify-center mx-auto mb-3">
                <MessageSquare size={20} className="text-trippy-500" />
              </div>
              <p className="text-sm font-medium text-foreground">Chat with Trippy AI</p>
              <p className="text-xs text-muted mt-1 max-w-[250px] mx-auto">
                Ask me to modify your trip — swap activities, change restaurants, adjust pace, or add new experiences.
              </p>
            </div>
          )}

          {chatMessages.map((msg, i) => (
            <motion.div key={i} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
              {msg.role === "user" ? (
                <div className="flex justify-end">
                  <div className="max-w-[85%] px-3.5 py-2 rounded-2xl rounded-br-sm bg-trippy-500 text-white text-xs leading-relaxed shadow-sm">
                    {msg.content}
                  </div>
                </div>
              ) : (
                <div className="space-y-2">
                  {msg.changes && msg.changes.length > 0 && (
                    <div className="space-y-1.5">
                      {msg.changes.map((c, ci) => (
                        <motion.div key={ci} initial={{ opacity: 0, x: -10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: ci * 0.1 }}
                          className={`flex items-start gap-2.5 px-3 py-2.5 rounded-xl border text-xs ${
                            c.type === "swap" ? "border-blue-200 bg-blue-50/80" :
                            c.type === "add" ? "border-green-200 bg-green-50/80" :
                            c.type === "remove" ? "border-red-200 bg-red-50/80" :
                            "border-amber-200 bg-amber-50/80"
                          }`}
                        >
                          <div className={`w-6 h-6 rounded-full flex items-center justify-center shrink-0 ${
                            c.type === "swap" ? "bg-blue-500" : c.type === "add" ? "bg-green-500" : c.type === "remove" ? "bg-red-500" : "bg-amber-500"
                          }`}>
                            {c.type === "swap" ? <ArrowRightLeft size={11} className="text-white" /> :
                             c.type === "add" ? <Plus size={11} className="text-white" /> :
                             c.type === "remove" ? <Trash2 size={11} className="text-white" /> :
                             <Lightbulb size={11} className="text-white" />}
                          </div>
                          <div className="flex-1 min-w-0">
                            {c.dayNumber && <span className="font-bold text-foreground">Day {c.dayNumber} · </span>}
                            <span className="text-foreground/80">{c.summary}</span>
                          </div>
                        </motion.div>
                      ))}
                    </div>
                  )}
                  {(!msg.changes || msg.changes.length === 0) && (
                    <div className="px-3.5 py-2.5 rounded-2xl rounded-bl-sm bg-[#f4f4f0] text-xs text-foreground leading-relaxed">
                      {msg.content.split("\n").map((line, li) => {
                        if (line.includes("**")) return <p key={li} className="font-semibold mt-1">{line.replace(/\*\*/g, "")}</p>;
                        if (line.startsWith("•") || line.startsWith("-")) return <p key={li} className="pl-2 text-muted">{line}</p>;
                        if (line.startsWith("*") && line.endsWith("*")) return <p key={li} className="italic text-[10px] text-trippy-600 mt-1">{line.replace(/\*/g, "")}</p>;
                        return line ? <p key={li}>{line}</p> : <br key={li} />;
                      })}
                    </div>
                  )}
                  {msg.hasModification && (
                    <div className="flex items-center gap-1.5 text-[10px] text-green-600 font-medium pl-1">
                      <Check size={10} /> Trip updated — see itinerary →
                    </div>
                  )}
                </div>
              )}
            </motion.div>
          ))}

          {chatLoading && (
            <div className="flex justify-start">
              <div className="bg-[#f4f4f0] px-4 py-3 rounded-2xl rounded-bl-sm flex items-center gap-2">
                <Loader2 size={14} className="animate-spin text-trippy-500" />
                <span className="text-xs text-muted">Modifying your trip…</span>
              </div>
            </div>
          )}
          <div ref={chatEndRef} />
        </div>

        {/* Chat input */}
        <form
          onSubmit={(e) => { e.preventDefault(); void handleChatSend(); }}
          className="px-4 py-3 border-t border-border/60 bg-white"
        >
          <div className="flex items-center gap-2 bg-[#f7f6f3] rounded-xl px-3 py-2">
            <input
              value={chatInput}
              onChange={(e) => setChatInput(e.target.value)}
              placeholder="Ask anything..."
              className="flex-1 text-sm bg-transparent outline-none placeholder:text-muted/50"
            />
            <button type="submit" disabled={chatLoading || !chatInput.trim()}
              className="w-8 h-8 rounded-full bg-trippy-500 flex items-center justify-center text-white disabled:opacity-30 cursor-pointer hover:bg-trippy-600 transition-colors shadow-sm"
            >
              <Send size={14} />
            </button>
          </div>
        </form>
      </motion.div>

      {/* ── RIGHT: Trip Details ────────────────────────────────────── */}
      <motion.div
        className="relative z-10 flex-1 overflow-y-auto"
        initial={{ opacity: 0, x: 20 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ delay: 0.15 }}
      >
        <div className="max-w-3xl mx-auto px-6 py-6 space-y-6">
          {/* Hero image + info */}
          <div className="relative rounded-2xl overflow-hidden h-56 shadow-lg">
            <img
              src={draftTrip.image}
              alt={draftTrip.destination}
              className="w-full h-full object-cover"
              onError={(e) => { (e.target as HTMLImageElement).src = "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&auto=format&fit=crop&q=80"; }}
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/20 to-transparent" />
            <div className="absolute bottom-4 left-5 right-5">
              <h1 className="text-white font-bold text-xl drop-shadow-lg">
                {actualDays > 0 ? `${draftTrip.destination} — ${actualDays}-Day Trip` : draftTrip.title}
              </h1>
              <div className="flex items-center gap-3 mt-1.5">
                <span className="flex items-center gap-1 text-white/90 text-xs"><MapPin size={12} /> {draftTrip.destination}</span>
                <span className="flex items-center gap-1 text-white/90 text-xs"><Star size={12} fill="currentColor" className="text-amber-400" /> {draftTrip.rating}</span>
              </div>
            </div>
            {/* X button = close entire view */}
            <button
              onClick={onClose}
              className="absolute top-4 right-4 w-8 h-8 rounded-full bg-black/30 backdrop-blur-sm flex items-center justify-center text-white hover:bg-black/50 cursor-pointer transition-colors"
            >
              <X size={16} />
            </button>
          </div>

          {/* Trip stats */}
          <div className="flex flex-wrap gap-3">
            {[
              { icon: <Calendar size={14} />, label: displayDuration, color: "bg-trippy-500/10 text-trippy-700" },
              { icon: <DollarSign size={14} />, label: draftTrip.budget, color: "bg-amber-500/10 text-amber-700" },
              { icon: <Users size={14} />, label: `${draftTrip.groupSize} people`, color: "bg-blue-500/10 text-blue-700" },
              { icon: <Sparkles size={14} />, label: `${totalActivities} activities`, color: "bg-purple-500/10 text-purple-700" },
            ].map((s, i) => (
              <div key={i} className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium ${s.color}`}>
                {s.icon} {s.label}
              </div>
            ))}
            {draftTrip.bestTimeToVisit && (
              <div className="flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium bg-green-500/10 text-green-700">
                <Calendar size={14} /> Best: {draftTrip.bestTimeToVisit}
              </div>
            )}
          </div>

          {/* Highlights */}
          {draftTrip.highlights.length > 0 && (
            <div className="flex flex-wrap gap-2">
              {draftTrip.highlights.map(h => (
                <span key={h} className="text-[11px] bg-white border border-border/60 px-3 py-1 rounded-full text-foreground/70 shadow-sm">
                  {h}
                </span>
              ))}
            </div>
          )}

          {/* Itinerary */}
          {itineraryLoading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 size={24} className="animate-spin text-trippy-500 mr-3" />
              <span className="text-sm text-muted">Generating your itinerary…</span>
            </div>
          ) : draftTrip.aiItinerary && draftTrip.aiItinerary.length > 0 ? (
            <div>
              <h2 className="text-sm font-bold text-foreground flex items-center gap-2 mb-3">
                <Sparkles size={14} className="text-trippy-500" />
                Your Itinerary
                <span className="text-[10px] font-normal text-muted ml-1">(hover activities to edit)</span>
              </h2>

              {draftTrip.aiItinerary.map((day, dayIdx) => {
                const isExpanded = expandedDays.has(day.dayNumber);
                const isEditingThisDay = editingDayNum === day.dayNumber;
                const dateStr = day.date
                  ? new Date(day.date).toLocaleDateString(undefined, { weekday: "long", day: "numeric", month: "short" })
                  : "";

                return (
                  <div key={day.dayNumber} className="mb-3">
                    <div className="rounded-xl border border-border/60 overflow-hidden bg-white shadow-sm">
                      {/* Day header */}
                      <div className="flex items-center gap-3 px-4 py-3 hover:bg-trippy-500/[0.02] transition-colors">
                        <button
                          onClick={() => toggleDay(day.dayNumber)}
                          className="flex-1 flex items-center gap-3 text-left cursor-pointer min-w-0"
                        >
                          <div className="w-9 h-9 rounded-xl bg-trippy-500 text-white text-xs flex items-center justify-center font-bold shadow-sm shrink-0">
                            D{day.dayNumber}
                          </div>
                          <div className="flex-1 min-w-0">
                            {isEditingThisDay ? (
                              <input
                                value={editDayTitle}
                                onChange={(e) => setEditDayTitle(e.target.value)}
                                onKeyDown={(e) => {
                                  if (e.key === "Enter") saveEditDay();
                                  if (e.key === "Escape") setEditingDayNum(null);
                                }}
                                onClick={(e) => e.stopPropagation()}
                                autoFocus
                                className="text-sm font-bold text-foreground bg-transparent border-b-2 border-trippy-400 outline-none w-full pb-0.5"
                              />
                            ) : (
                              <p className="text-sm font-bold text-foreground truncate">{day.title}</p>
                            )}
                            {dateStr && <p className="text-[10px] text-muted">{dateStr}</p>}
                          </div>
                          <span className="text-[10px] text-muted bg-surface px-2.5 py-0.5 rounded-full shrink-0">
                            {day.activities.length} activities
                          </span>
                          {isExpanded ? <ChevronUp size={14} className="text-muted shrink-0" /> : <ChevronDown size={14} className="text-muted shrink-0" />}
                        </button>

                        {/* Edit / Save day title button */}
                        {isEditingThisDay ? (
                          <div className="flex items-center gap-1.5 shrink-0">
                            <button
                              onClick={saveEditDay}
                              className="text-[10px] font-semibold text-white bg-trippy-500 px-2.5 py-1 rounded-full hover:bg-trippy-600 cursor-pointer transition-colors"
                            >
                              Save
                            </button>
                            <button
                              onClick={() => setEditingDayNum(null)}
                              className="text-[10px] text-muted border border-border px-2.5 py-1 rounded-full hover:text-foreground cursor-pointer transition-colors"
                            >
                              Cancel
                            </button>
                          </div>
                        ) : (
                          <button
                            onClick={(e) => { e.stopPropagation(); startEditDay(day.dayNumber, day.title); }}
                            title="Edit day title"
                            className="shrink-0 w-7 h-7 rounded-lg flex items-center justify-center text-muted hover:text-trippy-600 hover:bg-trippy-500/10 transition-colors cursor-pointer"
                          >
                            <Pencil size={12} />
                          </button>
                        )}
                      </div>

                      <AnimatePresence>
                        {isExpanded && (
                          <motion.div
                            initial={{ height: 0 }}
                            animate={{ height: "auto" }}
                            exit={{ height: 0 }}
                            className="overflow-hidden"
                          >
                            <div className="divide-y divide-border/30 border-t border-border/40">
                              {day.activities.map((act, idx) => {
                                const cat = String((act as Record<string, unknown>).category || "");
                                const isEditingThis =
                                  editingActivity?.dayNumber === day.dayNumber &&
                                  editingActivity?.idx === idx;

                                return (
                                  <div key={idx} className="group relative">
                                    {isEditingThis ? (
                                      /* ── Inline edit form ── */
                                      <div className="px-4 py-3 bg-trippy-500/[0.025] space-y-2.5 border-l-2 border-trippy-400">
                                        <p className="text-[10px] font-semibold text-trippy-700 uppercase tracking-wider">Edit Activity</p>
                                        <div className="grid grid-cols-2 gap-2">
                                          <input
                                            value={editActivityForm.title}
                                            onChange={(e) => setEditActivityForm(f => ({ ...f, title: e.target.value }))}
                                            placeholder="Activity title *"
                                            autoFocus
                                            className="col-span-2 text-xs rounded-lg border border-trippy-300 px-2.5 py-1.5 outline-none bg-white focus:border-trippy-500"
                                          />
                                          <input
                                            value={editActivityForm.time}
                                            onChange={(e) => setEditActivityForm(f => ({ ...f, time: e.target.value }))}
                                            placeholder="Time (e.g. 10:00 AM)"
                                            className="text-xs rounded-lg border border-border px-2.5 py-1.5 outline-none bg-white focus:border-trippy-500/50"
                                          />
                                          <input
                                            value={editActivityForm.estimatedCost}
                                            onChange={(e) => setEditActivityForm(f => ({ ...f, estimatedCost: e.target.value }))}
                                            placeholder="Cost (e.g. $20)"
                                            className="text-xs rounded-lg border border-border px-2.5 py-1.5 outline-none bg-white focus:border-trippy-500/50"
                                          />
                                          <input
                                            value={editActivityForm.location}
                                            onChange={(e) => setEditActivityForm(f => ({ ...f, location: e.target.value }))}
                                            placeholder="Location / Address"
                                            className="col-span-2 text-xs rounded-lg border border-border px-2.5 py-1.5 outline-none bg-white focus:border-trippy-500/50"
                                          />
                                          <textarea
                                            value={editActivityForm.description}
                                            onChange={(e) => setEditActivityForm(f => ({ ...f, description: e.target.value }))}
                                            placeholder="Description (optional)"
                                            rows={2}
                                            className="col-span-2 text-xs rounded-lg border border-border px-2.5 py-1.5 outline-none bg-white resize-none focus:border-trippy-500/50"
                                          />
                                        </div>
                                        <div className="flex gap-2">
                                          <button
                                            onClick={saveEditActivity}
                                            disabled={!editActivityForm.title.trim()}
                                            className="text-[10px] font-semibold text-white bg-trippy-500 px-3.5 py-1.5 rounded-full cursor-pointer hover:bg-trippy-600 disabled:opacity-40 transition-colors"
                                          >
                                            Save changes
                                          </button>
                                          <button
                                            onClick={() => setEditingActivity(null)}
                                            className="text-[10px] text-muted border border-border px-3.5 py-1.5 rounded-full cursor-pointer hover:text-foreground transition-colors"
                                          >
                                            Cancel
                                          </button>
                                        </div>
                                      </div>
                                    ) : (
                                      /* ── Activity row ── */
                                      <div className="flex gap-3 px-4 py-3 hover:bg-trippy-500/[0.02] transition-colors">
                                        <div className="shrink-0 pt-0.5 w-14 text-center">
                                          {act.time ? (
                                            <span className="text-[10px] font-bold text-trippy-600 bg-trippy-500/10 px-2 py-0.5 rounded-md">{act.time}</span>
                                          ) : (
                                            <div className="w-2 h-2 rounded-full bg-trippy-300 mx-auto mt-1.5" />
                                          )}
                                        </div>
                                        <div className="flex-1 min-w-0">
                                          <div className="flex items-center gap-2 flex-wrap">
                                            <span className="text-xs font-semibold text-foreground">{act.title}</span>
                                            {cat && (
                                              <span className={`text-[9px] font-medium px-2 py-0.5 rounded-full border ${CAT_COLORS[cat] || "bg-gray-100 text-gray-600 border-gray-200"}`}>
                                                {CAT_ICONS[cat] || "📌"} {cat.toLowerCase()}
                                              </span>
                                            )}
                                          </div>
                                          {act.description && (
                                            <p className="text-[11px] text-muted mt-0.5 leading-relaxed">{act.description}</p>
                                          )}
                                          <div className="flex flex-wrap items-center gap-2 mt-1.5">
                                            {act.location && (
                                              <span className="text-[10px] text-muted flex items-center gap-0.5">
                                                <MapPin size={9} className="text-trippy-400" /> {act.location}
                                              </span>
                                            )}
                                            {act.estimatedCost && (
                                              <span className="text-[10px] font-semibold text-amber-700 bg-amber-50 border border-amber-200 px-2 py-0.5 rounded-md">
                                                {act.estimatedCost}
                                              </span>
                                            )}
                                          </div>
                                        </div>
                                        {/* Edit / Delete (visible on hover) */}
                                        <div className="shrink-0 flex items-start gap-1 opacity-0 group-hover:opacity-100 transition-opacity pt-0.5">
                                          <button
                                            onClick={() => startEditActivity(day.dayNumber, idx, act)}
                                            title="Edit activity"
                                            className="w-6 h-6 rounded-lg flex items-center justify-center text-muted hover:text-trippy-600 hover:bg-trippy-500/10 transition-colors cursor-pointer"
                                          >
                                            <Pencil size={10} />
                                          </button>
                                          <button
                                            onClick={() => deleteActivity(day.dayNumber, idx)}
                                            title="Delete activity"
                                            className="w-6 h-6 rounded-lg flex items-center justify-center text-muted hover:text-red-500 hover:bg-red-50 transition-colors cursor-pointer"
                                          >
                                            <Trash2 size={10} />
                                          </button>
                                        </div>
                                      </div>
                                    )}
                                  </div>
                                );
                              })}

                              {/* Add activity */}
                              <div className="px-4 py-2.5">
                                <button
                                  onClick={() => addActivity(day.dayNumber)}
                                  className="flex items-center gap-1.5 text-[10px] font-semibold text-trippy-600 hover:text-trippy-700 cursor-pointer transition-colors"
                                >
                                  <Plus size={11} className="text-trippy-500" /> Add activity
                                </button>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                  </div>
                );
              })}
            </div>
          ) : null}

          {/* Save bar */}
          <div className="sticky bottom-0 bg-[#f7f6f3] pt-3 pb-4">
            <Button className="w-full text-sm py-3" onClick={onSave} disabled={saved}>
              {saved ? <><Check size={16} /> Trip Saved</> : <><Sparkles size={16} /> Save Trip</>}
            </Button>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}
