spring:
  config:
    import: "optional:file:../../infra/docker/.env[.properties]"
  application:
    name: chat-service
  main:
    allow-circular-references: true
  devtools:
    livereload:
      enabled: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5434}/${POSTGRES_DB:trippy_db}?currentSchema=chat_schema
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: ChatServicePool
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: chat_schema
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}
    virtual-host: ${RABBITMQ_DEFAULT_VHOST:trippy}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8083

trippy:
  trip-service:
    url: ${TRIP_SERVICE_URL:http://localhost:8082}
  chat:
    upload-dir: ./uploads/chat

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    pse.trippy.chatservice: INFO
    org.hibernate.SQL: WARN
    org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator: ERROR
    org.springframework.messaging.simp.stomp.StompBrokerRelayMessageHandler: ERROR
    reactor.netty.tcp.TcpClient: ERROR
