# ─── Application ─────────────────────────────────────────────
spring.application.name=notification-service
server.port=8085
spring.devtools.livereload.enabled=false

# ─── PostgreSQL ──────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5434/trippy_db?currentSchema=notification_schema
spring.datasource.username=${DB_USERNAME:trippy_admin}
spring.datasource.password=${DB_PASSWORD:change_me_postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=notification_schema
spring.jpa.open-in-view=false
logging.level.org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator=ERROR

# ─── Spring Mail ─────────────────────────────────────────────
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:noreply@trippy.local}
spring.mail.password=${MAIL_PASSWORD:placeholder}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ─── RabbitMQ ────────────────────────────────────────────────
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${MQ_USERNAME:trippy_mq}
spring.rabbitmq.password=${MQ_PASSWORD:change_me_rabbitmq}
spring.rabbitmq.virtual-host=trippy

# ─── Actuator ────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,info
